### ISSUE TITLE
change screen orientation

### ISSUE THREAD

**Issue by leahwang1962** [kklmn/xrt#105]
Hi,
Can we set the screen surface perpendicular to the prime exit beam, when the prime exit ray has a angle with global Y axis? 
Thanks

**Comment by kklmn** [comment]
Hi,
Yes, you need to change the screen's x and/or z local axes in its [constructor](https://xrt.readthedocs.io/raycing.html?highlight=screen#xrt.backends.raycing.screens.Screen).

**Comment by leahwang1962** [comment]
Thanks for the suggestion. Sorry I still have difficulty to implement them.
If I changed screen's x=[0.022826,-0.999739,0] z=auto, I found the screen Y is not perpendicular to screen surface anymore.

One step further, if I set screen's x=[0.022826,-0.999739,0] z=[0,0.999739,-0.022826], the z will not be on screen's surface.
Appreciate if you can correct my parameters usage.


![Y not perpendicular to sensor surface](https://user-images.githubusercontent.com/99756010/159746685-9f15a947-d4ba-474a-b494-aff19301dcb6.jpg)
![Z out off sensor surface](https://user-images.githubusercontent.com/99756010/159746729-6968deec-5902-44b9-ad36-349787836aff.jpg)
[CMF18.5-11.5Cu15_VertFirst_Screentilt.zip](https://github.com/kklmn/xrt/files/8334730/CMF18.5-11.5Cu15_VertFirst_Screentilt.zip)

**Comment by kklmn** [comment]
Where do you set x and z: inside or outside of the screen's constructor?

**Comment by kklmn** [comment]
I see now, it is not a script but in a Qook's xml.

**Comment by kklmn** [comment]
This is due to different scaling factors along xyz. Make them equal if you want to preserve angles.

**Comment by kklmn** [comment]
What kind of help do you need? How to define 3 coordinates of 2 vectors?

**Comment by leahwang1962** [comment]
Yes, I already defined x z coordinates of 2 vectors for tilted sensor surface to be perpendicular to incident prime beam. Then how can I  combine the 45 degree rotation to the already tilted 3 coordinates of 2 vectors? Thanks.

**Comment by kklmn** [comment]
ok, in case your goggle is broken: [here](https://math.stackexchange.com/questions/511370/how-to-rotate-one-vector-about-another)

**Comment by kklmn** [comment]
...and for 45 deg this is much easier:
**x'** = **x** + **z**, 
**z'** = **z** - **x**

**Comment by leahwang1962** [comment]
It is in the correct direction, however the final result looks to me the rotation is not 45 degree(bigger than 45) by using the above equation
 x' = Xt + Zr,
z' = Zt - Xr  (t is tilt vector, r is 45 rotation vector). 
Not sure which step is wrong.
![Is rotation over 45](https://user-images.githubusercontent.com/99756010/159974764-83850ee0-ff4e-4810-9249-6b9f783f18a5.jpg)

**Comment by kklmn** [comment]
Is something in my previous message unclear? The 6 bold letters are vectors.

**Comment by leahwang1962** [comment]
I am not so sure about the x and z on the right side of your equations. I think the first column x,z should represent tilited vector and second column x,z are rotation vectors. The final vectors are combining the effects of tilting and rotation.
The below are my calculation:
tilt vectors
Xt=[0.999739,-0.022826,0] Zt=[0,-0.022826,0.999739]
rotation vectors
Xr=[0.707,0,0.707] Zr= [-0.707,0,0.707]
 so the final vectors combining tilt and rotation after normalization will be:
x'=Xt+Zr=[0.382391,-0.02982,0.92352]
z'=Zt-Xr=[-0.92352,-0.02982,0.382391]

Thanks.

**Comment by kklmn** [comment]
**x** and **z** are the non-rotated local axes. The primed ones are rotated. Don't forget to make them unit length.

**Comment by leahwang1962** [comment]
Now works perfectly. Sorry for my misunderstanding. Thank you so much.
