### ISSUE TITLE
test_laue_bent.py Segmentation Fault

### ISSUE THREAD

**Issue by glebdovzhenko** [kklmn/xrt#107]
Hello,

I've been trying to run the `test_laue_bent.py` example you have provided, and I've run into a segmentation fault when I run the script as it is. If I change `calcBorrmann` in `CrystalSi` constructor to anything else, it works.
Do you have any advice on how to debug this?

I've been having a pretty bad time overall trying to run OpenCL on my MacBook, so that is probably a connected issue. So far I managed to make most things work by only using the CPU (apparently the GPU drivers for MBPs are known to be unreliable), but now there's this error. Maybe you have some ideas?

**Comment by kklmn** [comment]
How do you run it? From an IDE?

**Comment by glebdovzhenko** [comment]
> How do you run it? From an IDE?

Usually I run it from PyCharm, but terminal gives the same message.

**Comment by kklmn** [comment]
What do you want from this example? Do you need the Borrmann triangle?

**Comment by kklmn** [comment]
For getting the Borrmann triangle you do need a powerful GPU; your MBP is not an appropriate machine.

If you haven't seen it, [this example](https://xrt.readthedocs.io/gallery2.html#laue-monochromator) might give you what you need. This one can easily run on a laptop. For each ray, it calculates local reflectivity/transmittivity given the incidence angle and the local crystal orientation at the impact point.
