### ISSUE TITLE
to run MontelMirror.py using user interface 

### ISSUE THREAD

**Issue by leahwang1962** [kklmn/xrt#108]
Hello,
 I made a user interface by QT designer, so the user can type in  optic parameters and click a pushbutton to start  running build_beamline in MontelMirror.py connected by a def of optic, and several important def are show below. However the  rs.GeometricSource gave me error:
Process finished with exit code -1073740791 (0xC0000409).
Can you provide advice or a very simple code how to run your MontelMirror.py by  clicking a button in user interface?
Thanks

class MyWindow(QtWidgets.QDialog,Ui_Dialog):
        def __init__(self):
            #QtWidgets.QDialog.__init__(self)
            super(MyWindow, self).__init__()
            self.setupUi(self)
            self.pushButton.clicked.connect(self.optic)
 def optic(self):
            beamLine = self.build_beamline()
 def build_beamline(nrays=raycing.nrays):
            beamLine = raycing.BeamLine(height=0)

            rs.GeometricSource(
                beamLine, 'GeometricSource', (0, 0, 0),
                nrays=nrays, dx=0., dz=0., dxprime=2e-4, dzprime=1e-4,
                distE='lines', energies=(E0,), polarization='horizontal')

**Comment by kklmn** [comment]
How do you know it was rs.GeometricSource? What was the full error message?
How do you start your qt program? From an IDE?

**Comment by leahwang1962** [comment]
For debugging, I deleted all  codes after rs.GeometricSource, and the code line beamLine = raycing.BeamLine(height=0)  before rs.GeometricSource works fine. 
The full error message is: Process finished with exit code -1073740791 (0xC0000409).

 I converted qt program from ui to py(saved as myModule.py). In my modified MontelMirror.py I added "from myModule import Ui_Dialog".  When MontelMirror.py started, the user interface dialogbox pops up. After user types in some  optic parameters, and  click a pushbutton on this dialogbox, the program will go to def build_beamline(nrays=raycing.nrays):

I am using Pycharm to run the program.
Attached here are several files I mentioned above. 
Thanks,

[Ui.zip](https://github.com/kklmn/xrt/files/8412166/Ui.zip)

**Comment by kklmn** [comment]
Try to start it without any IDE, just from a pure terminal.

**Comment by leahwang1962** [comment]
here is the error message if I run from pure terminal:

>>> os.system('Inerface_xrt_connection.py')
Traceback (most recent call last):
  File "C:\pycharm\Projects\20220222_xrt\CMFSimulation\OpticInterface\Inerface_xrt_connection.py", line 51, in optic
    beamLine = self.build_beamline()
  File "C:\pycharm\Projects\20220222_xrt\CMFSimulation\OpticInterface\Inerface_xrt_connection.py", line 66, in build_beamline
    rs.GeometricSource(
  File "C:\Python\lib\site-packages\xrt\backends\raycing\sources_geoms.py", line 216, in __init__
    self.nrays = np.long(nrays)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'MyWindow'
-1073740791

**Comment by kklmn** [comment]
in `build_beamline(nrays=raycing.nrays)` the 1st argument must be `self`.

**Comment by leahwang1962** [comment]
It works. Thanks a lot.
