### ISSUE TITLE
cffi error when running xrtQoot

### ISSUE THREAD

**Issue by y19880621** [kklmn/xrt#11]
Dear Sir or Madam,
I am a novice to XRT. Recently, I installed the xrt-master version to learn the software. When I tried to run some examples, an error related to "cffi" always occurred (detailed information at the end). I checked the python packages and the cffi package was indeed installed. As following:

> Requirement already satisfied: cffi==1.11.2 from file:///D:/Downloads/GoogleDownloads/cffi-1.11.2-cp27-cp27m-win_amd64.whl in c:\python27\lib\site-packages
Requirement already satisfied: pycparser in c:\python27\lib\site-packages (from cffi==1.11.2)

How could I solve the problem? Thank you.

detailed information:
[error.txt](https://github.com/kklmn/xrt/files/1516364/error.txt)

**Comment by yxrmz** [comment]
Thanks for your feedback. I've restructured the automatic alignment procedure, all examples should work now.

**Comment by y19880621** [comment]
Thank you for your update. The examples work properly.

Best,
Yiming

杨一鸣
