### ISSUE TITLE
Where I can set random seed

### ISSUE THREAD

**Issue by Tony1886** [kklmn/xrt#112]
Hello, I want to set a random seed to ensure the same results I can get every time. I have tried np.random.seed(1), but it doesn't work, what should I do?

**Comment by kklmn** [comment]
Hi, you can set it anywhere before the first use, i.e. before generating the photon source. It does work in my examples.

**Comment by Tony1886** [comment]
Thank you for your response. I make a simple mistake and now it works. But I still have some problems about creating laterally graded multilayer. I know it should modify the method `get_b_thichness `and 'get_t_thickness', but  I can't understand the independent variables x and y， how can I extract the value from the Elliptical Mirror. Please give me some explanation or show me some examples.

**Comment by kklmn** [comment]
The point of making graded multilayers is to grow them on a flat support. What's your point in growing a complex structure on a complex surface?

You can have local x and y from a parametric representation like this:
```
    r = self.local_r(s, phi)
    x, y, z = self.param_to_xyz(s, phi, r)
```

**Comment by Tony1886** [comment]
I want to simulate Gobel Mirror, which is paraboloid or ellipsoid Mirror Coated with laterally graded multilayer. So I generate a  graded multilayer and give it to  Elliptical Mirror as the material. I konw the local x and y belong to the OE(Elliptical Mirror), but how to contract to the material(laterally graded multilayer)?

**Comment by kklmn** [comment]
The two arrays given to `get_t_thickness` and `get_b_thickness` are local `x` and `y` for non-parametric (Cartesian) OEs or local `s` and `phi` for parametrically defined OEs, as explained in the methods' docstrings.

The parameterization of `ParabolicalMirrorParam` and `EllipticalMirrorParam` is explained in their docstrings.

For your application, I would use the parametric coordinates to define the graded thickness. If you want local `x` and `y` in your definitions, you can get them from the parametric coordinates, as I showed in my previous post.

**Comment by leahwang1962** [comment]
I am sorry if it is not appropriate to jump into your conversation. Recently I start to work on ray tracing of lateral grading or periodical multilayer coating effects on Montel mirrors. The mirrors are Elliptical. Very similar projects as Tony1886 is doing. However I have no clue where to start. I would like to ask if KKlmn or Tony1886 can share some  .py  or .xml files , so I don't need to start from zero. Thanks.

**Comment by Tony1886** [comment]
> The two arrays given to `get_t_thickness` and `get_b_thickness` are local `x` and `y` for non-parametric (Cartesian) OEs or local `s` and `phi` for parametrically defined OEs, as explained in the methods' docstrings.
> 
> The parameterization of `ParabolicalMirrorParam` and `EllipticalMirrorParam` is explained in their docstrings.
> 
> For your application, I would use the parametric coordinates to define the graded thickness. If you want local `x` and `y` in your definitions, you can get them from the parametric coordinates, as I showed in my previous post.

Thank you for you comment. In fact, I just figured it out a few days ago. The method 'get_t_thickness' could help to generate a montel mirror. The thickness of multiple layer is a function of local 'y', so the following code can be used to get the local `y`

`def get_t_thickness(self, x, y, iPair):
        locx, locy, locz = beamLine.MirrorV.param_to_xyz(x, y, beamLine.MirrorV.local_r(x, y))`

Where `beamLine.MirrorV` is the `EllipticalMirrorParam`
So, the local coordinate can be achieved, as follows:
![Figure_2](https://user-images.githubusercontent.com/38371437/176918816-8b5fbe14-8980-4256-b0ab-f3782e3f3b5b.png)

The method do work for me, but I'm not sure if there is a better way.

I am sorry for the late reply， I am not good at python, so it take me some time to learn.
