### ISSUE TITLE
How to realize global rotate of OE

### ISSUE THREAD

**Issue by Tony1886** [kklmn/xrt#118]
I have created a montel optics, which includs two elliptical Mirrors. I want to realize global rotate, what should I do? I noticed that the OE only has local rotate  function.

**Comment by kklmn** [comment]
Hi, I see your issue #112 ends with my comment, not yours. I don't mean a few words of politeness (although this is also naturally expected) but rather a brief summary of how did it work. Were my replies usable or understandable at all? Please fill the vacuum there before I do anything here.

**Comment by kklmn** [comment]
Our definitions of coordinate systems can be seen [here](https://xrt.readthedocs.io/raycing.html#coordinate-systems). Your definitions are probably different. In practice, how would you rotate a device around a very distant point? You anyways achieve it through _local_ rotations and translations. So please explain what you want to get.

**Comment by Tony1886** [comment]
My probem can be described as follows:
![图片1](https://user-images.githubusercontent.com/38371437/177936489-360fa9fe-439e-462c-8998-8ca83e71e2fe.png)
:
Fig. (a) is my coordinate defination, which is corresponding with xrt system. The blue box denotes the source, and the gray boxes present the Montel optics.
I want to realize global rotation, which is shown as Fig. (b), the source and mirrors rotate around the point together.
But in xrt, the rotation is based on local rotation.
I do think that global  rotation can be represented by local rotation，is there simple way to realize what I want in xrt? Could you give me some suggestions, thank you

**Comment by kklmn** [comment]
I think this is directly possible in xrt. The positions of all elements (`center`) are given in the global system and the local beamline system is rotated by `azimuth` parameter of your `Beamline` instance.
