### ISSUE TITLE
VLS grating

### ISSUE THREAD

**Issue by zzw840** [kklmn/xrt#119]
Hi I am a beamlines scientist on a soft x-ray spectroscopy beamline in China. I am tring to use XRT to run some simulations on various gratings, such as VLS spherical grating and plane grating. May I ask what module I should use? 

I found VLSLaminarGrating class but it does not have the option to go with spherical or plane. Also I could not get it to run correctly and got a flash quit of the whole GUI. Anyone has a working template on this class that can be shared?? 

Very much appreciated for any help on this!

**Comment by kklmn** [comment]
Hi,

If you need ray tracing, you can use any descendant of [OE](https://xrt.readthedocs.io/raycing.html#xrt.backends.raycing.oes.OE). Specify _gratingDensity_ as needed. 

If you need it in wave propagation, you have to define the surface of each grating facet (elevation by local_z(x, y) and inclination by local_n(x, y)) in a descendant class, as was done for [BlazedGrating](https://xrt.readthedocs.io/raycing.html#xrt.backends.raycing.oes.BlazedGrating), see the description there. There are a few similar examples at the end of the module `xrt/backends/raycing/oes.py`.

**Comment by zzw840** [comment]
Thanks a lot for the guide! I think I solved the issue (or did not notice any problem as yet).
