### ISSUE TITLE
Comparing RayTracing reflectivity curves with calculations

### ISSUE THREAD

**Issue by emasimak** [kklmn/xrt#120]
Hi!

I want to model the reflectivity of (i) a mosaic graphite, (ii) a perfect graphite and (iii) a perfect silicon crystal. Specifically I want to derive the reflectivity curves from ray tracing and calculations.
I came across the test of a mosaic crystal ([1]) were you do exactly this and I attempted to extend this approach for what I want to do.

I define all crystals using the CrystalFromCell class, with (i) or w
ithout (ii-iii) mosaicity depending on the crystal.
For the calculation of the curves I use the get_amplitude_mosaic() and get_amplitude() functions accordingly.  
The beamline is built similarly to test_mosaic_xtal.py.

For the mosaic case the reflectivity curves from the ray tracing and the calculations match.
For the perfect crystal however they do not. I expected that they would.
I am attaching the relevant figures and the script that I am using in case it helps.

Could you suggest how to address this? or comment on whether there is something wrong with this approach?
Thank you for your time!

[1]: https://github.com/kklmn/xrt/blob/master/tests/raycing/test_mosaic_xtal.py

![perfectC](https://user-images.githubusercontent.com/23210247/184908891-6cd2179a-ecde-4495-a927-3d7ea81f0dc8.png)
![mosaic](https://user-images.githubusercontent.com/23210247/184908903-30176ef3-3cfc-4279-9daf-d0cb893716bd.png)
[xtalRefectivities_Comparison.zip](https://github.com/kklmn/xrt/files/9352091/xtalRefectivities_Comparison.zip)

**Comment by kklmn** [comment]
Hi,
Your calculated curves are functions of exact angles of incidence, whereas the ray-traced ones are ratios of two histograms (reflected over the incident). If you want them to coincide, the bin size should be set (much) smaller than the rocking curve width.

**Comment by emasimak** [comment]
Hi,
Thank you for the clarification and the fast reply! Tweaking the bins solved the issue.
