### ISSUE TITLE
Distribution function w for crystallite normals in mosaic crystals

### ISSUE THREAD

**Issue by bbazi** [kklmn/xrt#122]
Hi,
On line 1641 there is the Gaussian distribution function w for the crystallite normals in mosaic crystals.
For mosaic graphite crystals (HOPG,HAPG) we know that the rocking curve is better fitted by a Lorentzian distribution than by a Gaussian one.
Doesn't it make more sense if we would use a Lorentzian distribution for this function w `(w = 1 / (np.pi * self.mosaicity * (1 + (delta / self.mosaicity)**2)))` when we know from experiments that the rocking curve is Lorentzian shaped? Maybe one could specify between Gaussian and Lorentzian in the "get_amplitude_mosaic" function. I'm curious what you think of this.

**Comment by kklmn** [comment]
Hi,

>For mosaic graphite crystals (HOPG,HAPG) we know that the rocking curve is better fitted by a Lorentzian distribution than by a Gaussian one.

Who _we_? Mankind or a particular experimental group? Please provide a reference. So far, I see it contradicts (1) below, which follows Bacon & Lowde.

1. ["The mosaicity is commonly equated with the standard deviation of this distribution."](https://en.wikipedia.org/wiki/Mosaicity)
2. Lorentzian distribution doesn't have _standard deviation_ (rms).
3. It is certainly possible to derive new formulas and re-implement `get_amplitude_mosaic()` provided _you_ (in the above sense) provide convincing experimental evidence.

**Comment by bbazi** [comment]
Hi,
In the papers of Legall(2006), Legall(2009), Zastrau(2013) and Gerlach(2015), the rocking curves of HAPG crystals were best fit with a Lorenzian distribution. (not for HOPG, sorry for the confusion above)

Here are the citations:
- Legall, H., et al. "A new generation of X-ray optics based on pyrolytic graphite." Diamond 111, no. 21 (2006): 0-8.
- Legall, H., et al. "An efficient X-ray spectrometer based on thin mosaic crystal films and its application in various fields of X-ray spectroscopy." Journal of Applied Crystallography 42.4 (2009): 572-579.
- Zastrau, U., et al. "Characterization of strongly-bent HAPG crystals for von-Hámos x-ray spectrographs." Journal of Instrumentation 8.10 (2013): P10006.
- Gerlach, M., et al. "Characterization of HAPG mosaic crystals using synchrotron radiation." Journal of Applied Crystallography 48.5 (2015): 1381-1390.

**Comment by bbazi** [comment]
Hi,

Unfortunately, my knowledge one the reflectivity calculations is limited. My guess was, in the case of HAPG, to use a lorenzian distribution for w instead of a gaussian one. I was thinking of using the pdf from [https://en.wikipedia.org/wiki/Cauchy_distribution](url) and treating the scale parameter gamma as the mosaicity. If this is not the way to do it, I shall wait for you to implement this down the line.

No I don't have such an experimental setup available at the moment.

**Comment by bbazi** [comment]
I found a paper by Smid(2021) which presents a simulation code which takes into account the lorenzian distribution for HAPG, might be of interest to you. Unfortunately this code doesn't support the simulation of full cylinder crystal optics which I'm researching.

Paper: Šmíd, Michal, Xiayun Pan, and Katerina Falk. "X-ray spectrometer simulation code with a detailed support of mosaic crystals." Computer Physics Communications 262 (2021): 107811.
