### ISSUE TITLE
Mosaic crystals multiple reflections

### ISSUE THREAD

**Issue by bbazi** [kklmn/xrt#123]
Hi,
Does the xrt ray-tracing for mosaic crystals take into account multiple reflections as shown by Schlesiger(2017)? This is not really clear to me.
Schlesiger, Christopher, et al. "A new model for the description of X-ray diffraction from mosaic crystals for ray-tracing calculations." Journal of Applied Crystallography 50.5 (2017): 1490-1497.

Cheers, Benjamin

**Comment by kklmn** [comment]
Our mosaic modeling is described [here](https://xrt.readthedocs.io/raycing.html#xrt.backends.raycing.materials.Crystal), under _mosaicity_ parameter.

**Comment by bbazi** [comment]
Ah, the modeling by Sanchez del Rio doesn't take into account multiple reflections...
Thanks for the quick reply! Cheers
