### ISSUE TITLE
Diffraction from Mosaic crystal

### ISSUE THREAD

**Issue by emasimak** [kklmn/xrt#124]
Hi!

I want to simulate the diffraction of an x-ray beam from an HOPG crystal.
I define a geometrical source and monitor the beam size on the OE, using the global and the local beams. 
The diffracted beams that I get from the local beam seem a bit weird to me. To me it looks as if part of the beam is missing the crystal. I thought that maybe because of the low pitch angle indeed part of the beam was no hitting the crystal but I see that there are no "over" or "out" rays. Could you perhaps comment on why the beam profile looks like this? I do not get similar profiles when I use perfect crystals so I may be missing something obvious.

_Global beam_
![global_geoD](https://user-images.githubusercontent.com/23210247/188632342-e74a66c7-257a-42b3-b0a8-184a276b513f.png)
_Local beam_
![local_geoD](https://user-images.githubusercontent.com/23210247/188632346-034a64d7-f02b-45c1-bde7-4a8d2984647d.png)
[oneCrystal.zip](https://github.com/kklmn/xrt/files/9496747/oneCrystal.zip)

Thank you!

**Comment by kklmn** [comment]
Hi!

Mosaic crystals have an effect of secondary extinction, i.e. some noticeable penetration depth. We sample the impact points according to this secondary extinction distribution, see [Bacon and Lowde, Acta Crystallogr. 1, (1948) 303] for details. Those rays that go over the crystal thickness retain the original direction and also get some attenuation. Their x,y,z coordinates (the ray heads) do not lie on the crystal surface but represent the sampled impact points (also partly lying behind the crystal), so to plot them in a 2D XY plot becomes useless. You can still use them to study the secondary extinction effect: try to plot YZ or XZ to see the depth.

The rest of the rays (those sampled within the crystal depth) are reflected and also attenuated depending on the penetration depth.

You can study both parts by putting screens in the forward and the reflected direction.

**Comment by emasimak** [comment]
Hi!

Thank you very much for the quick reply and for the paper!
Your points are very clear. I am reading the paper now to get a better understanding of the ray treatment. Especially your point on the sampling points being partially behind the crystal.

In the mean time I wanted to ask if it is still the case that the mosaic crystals are only treated in the reflected geometry (https://github.com/kklmn/xrt/blob/master/xrt/backends/raycing/materials.py#L1048).
This forbids me from adding a screen in the forward (transmission) direction to monitor the beam after the crystal. 
This addition would be very helpful for the simulation I want to make. I am using a series of OEs and it would be very helpful to have the freedom to use the HOPG as a non-final element.

Thank you!

**Comment by kklmn** [comment]
> This forbids me from adding a screen in the forward (transmission) direction 

Not quite clear here. Why? I think, yes, you can put it there and monitor what is left from the direct beam.

The Laue case (the diffracted beam emerges from the back of the crystal) is formally implemented but never compared with external results, so I don't know if the implementation is correct. You can try it.

**Comment by kklmn** [comment]
The note in the docs "The mosaic case is implemented only in the reflection geometry" is about the calculation of the amplitude (only reflected but not transmitted). In ray-tracing, you nevertheless can use the forward part of the 'reflected' beam as we split the beam in our modeling of secondary extinction.

**Comment by emasimak** [comment]
Hi!
I hadn't though of accessing the forward beam without changing the geometry of the material. Thank you for the suggestion.
In my simulations I am using the Bragg geometry (this is what I need) and I am following your comment in https://github.com/kklmn/xrt/issues/110 to change between "reflected" and "transmitted" geometries. I get the global beams for each case, to which I expose my my monitoring screens in the diffracted and forward direction respectively. This is what I am doing so far.
How can I access the forward part of the 'reflected' beam without changing the geometry of the crystal?
After reading your comment I was looking for a propagate function and tried to use the "propagate_wave" function but I didn't manage to use it without errors.

Thank you!

**Comment by kklmn** [comment]
Hi!

The transmitted part for a tin mosaic crystal wasn't indeed implemented correctly. Now I've fixed it, created a new test example (`tests/raycing/test_mosaic_xtal_thin.py`) and extended the [docs](https://xrt.readthedocs.io/raycing.html#xrt.backends.raycing.materials.Crystal) under _mosaicity_ parameter.

Please use the new xrt version from GH and get back if the example and/or the description are unclear.

**Comment by emasimak** [comment]
Hi!

Thank you very much for the quick reply!
The example is very clear and with the updated code I can access the transmitted beam as well, thank you!
When I comment out the thickness of the crystal, there is no transmitted beam. From the updated docs, my understanding is that if no thickness is specified, a general infinitely thick crystal case is assumed.

Thank you!
