### ISSUE TITLE
ParabolicalMirror

### ISSUE THREAD

**Issue by leahwang1962** [kklmn/xrt#126]
Hello,
In xrtQook, I am building a (cylindrical)parabolical mirror with x^2=4py, p=0.12mm. Mirror center is at y=140.12mm, with mirror length 100mm. 
I thought it should be very simple, but can't build the mirror correctly and can't figure out the reason. 
I attached the mirror drawing and xml files here. 
Thanks for help.

![image](https://user-images.githubusercontent.com/99756010/191308232-7196dff7-b4b7-448c-ad71-c2737d0c027b.png)
[MF14-InfCu10 0.24.zip](https://github.com/kklmn/xrt/files/9609407/MF14-InfCu10.0.24.zip)

**Comment by kklmn** [comment]
Hi,

> I am building a (cylindrical)parabolical mirror with x^2=4py

Where and how do you use this equation?

What is your question?

**Comment by leahwang1962** [comment]
Appreciate your prompt reply.
I use the equation to calculate the mirror center (x,y,z) and LimphysX() used in xml file to build the parabolical mirror.
My question is how I can build this parabolical mirror in xrtQook, with the above given parameters. Using my attached xml file, when I click xrtGlow sunglass icon in xrtQook, the propagation at the bottom green bar will stop at 66%, and xrtGlow window never show up.

**Comment by kklmn** [comment]
And why do you think parabolicalMirrorParam uses the same equation?
It does have a parameter *p*. Why do you give it the value of _your_ *p*?

**Comment by leahwang1962** [comment]
I believe they are the sections I made the mistake, but I am not clear what is the correct way to do it. In manual , I read " focal distance p", that is why I though it is the same p as in my equation.   I also tried using f(0,0.12,0) without any luck.

Would you please give a simple xml file sample for parabolic mirror? I can't find any.
Thanks a lot.

**Comment by kklmn** [comment]
The *focal distance* of an optical element is the distance between the center of that element and a focus. Conventionally, we denote *p* as the upstream focal distance and *q* as the downstream focal distance. For a parabolic OE, only one of the two exists. Alternatively to *p* and *q* you can define *f1* and *f2* as 3D points in the global system.

If you search *.py files for `ParabolicalMirrorParam`, you can find a usage example in `tests/raycing/test_param_mirror.py`.

**Comment by leahwang1962** [comment]
Thanks. The test_param_mirror.py helps me to understand the parameters.
Now I copied all the parabolic parameters from test_param_mirror.py to xrtQook as below, but this mirror still can't finish initialization and xrtGlow doesn't show up. I had no difficult to add the elliptical mirror(also copied from test_param_mirror.py) in xrtQook and get xrtGlow. Very strange. 
![image](https://user-images.githubusercontent.com/99756010/192045140-0e987b0a-1c79-4724-8ef4-d7b502455e2d.png)

**Comment by leahwang1962** [comment]
Hello,
Is it possible there are some issue with Parabolic mirror in xrtQook?
I have run several parabolic mirrors with python (.py files), all of them work correctly and show expected results. Then I copied source, optic and screen parameters from these .py files to xrtQook, none of them can build a parabolic mirror successfully for xrtGlow to show.
Is it possible to have a look at this issue at your convenient time?
Thanks,
