### ISSUE TITLE
New to xrt, don't see 3D glasses for starting xrtGlow

### ISSUE THREAD

**Issue by dhabes** [kklmn/xrt#130]
Hi, I am brand new to the xrt program and feel completely overwhelmed with the installation process as I'm very inexperienced with these types of things. I haven't even used Python before, though I'm very interested in learning as I've used Matlab for the past 20 years and would like to do projects without a huge license cost.

Anyways, just giving a background so you understand how green I am. I want to design x-ray spectrometers/monochrometers with xrt. I tried to follow the instructions on https://xrt.readthedocs.io/. Here's what I've done so far:

- Installed Anaconda
- Installed xrt from the Anaconda prompt
- Started xrtQook using “python xrtQookStart.pyw”. Note, when starting xrtQook, it states "OpenGL not found" and "pyopencl not found." I'm not sure what those are, what they are used for, or where to go to install them.
- I have been working through the xrtQook tutorial (add bending magnet, crystal, screen, and changing properties)
- The next step is to view the beamline in xrtGlow but those 3D goggles which starts xrtGlow are not present in my tool bar of xrtQook. What do I need to do to have xrtGlow installed? I can't find info on that.

Please help!! Sorry I'm such a noob. Eventually I think this program will be awesome for my career but it will certainly be a rough start.

Cheers,
Dan

**Comment by kklmn** [comment]
Hi,

The 3D goggles need OpenGL, pyopencl is used for heavy calculations. The answers can be found  [here](https://xrt.readthedocs.io/instructions.html#instructions).

**Comment by dhabes** [comment]
Thanks for the reply kklmn!

From that page, I tried to do the automatic installation which says simply type "pip install xrt". I did that from the Anoconda command prompt and it showed a bunch of lines starting with "requirement already satisfied:" and then showed where the program/package was installed. Apparently there was already a version of xrt installed within Anoconda that I didn't know about located here:

c:\users\dhab\anaconda3\lib\site-packages\xrt-1.5.0-py3.9.egg

And the packages seem to be located here:

c:\users\dhab\anaconda3\lib\site-packages

However, the installer did not install OpenGL and I don't see it in the "site-packages" folder, so my 3D goggles are still not there when I load xrtQook (I've pasted the output of the install below). 

In the manual instructions it sends me to the Unofficial Windows Binaries for Python Extension Packages page. There is no OpenGL by itself, I only see pyopengl. Is that the one I need? And if so, there are TONS of versions listed for download. I have a 64 bit Windows system. Which one should I install? And are there other packages that I need which were not included in the auto install?

Thanks so much for your help!

![pip install xrt output](https://user-images.githubusercontent.com/116908362/198704855-baf984f6-b788-4012-9dac-95229d42a14d.png)

**Comment by dhabes** [comment]
Anyone have suggestions on the above question?
kklmn?

Thanks,
Dan

**Comment by kklmn** [comment]
Is the last paragraph in the section "Dependencies" in the above link not an answer?

**Comment by dhabes** [comment]
I don't know how I missed that! I was paying more attention to the automatic and manual installation parts.

I downloaded and installed everything mentioned in the dependencies and xrtGlow works now!!! Thank you so much!!!
