### ISSUE TITLE
Simple geometrical source beam propagation monitoring

### ISSUE THREAD

**Issue by emasimak** [kklmn/xrt#131]
Hi!

I am trying to simulate how the beam profile will change from a point in the experimental hutch onwards. The beam energy (10keV), size (2mm) and divergence (2.51urad) at that point are known. I plan to add OEs after this point but I want to understand how to set up this "dummy source" properly.
I am defining a geometrical source as follows: (If there is a better way to do this, I would be grateful to know)

```
    dx_FWHM = 2. # [mm] full width beam size: 2mm
    dx_sigma = dx_FWHM/2.355
    dz_FWHM = 2. # [mm] 
    dz_sigma = dz_FWHM/2.355
    dxprime_FWHM = 2.51e-6 # divergence: 2.51urad
    dxprime_sigma = dxprime_FWHM/2.355
    dzprime_FWHM = 2.51e-6 #
    dzprime_sigma = dzprime_FWHM/2.355

    beamLine = raycing.BeamLine()
    beamLine.source = rsources.GeometricSource(
        beamLine,
        center=[0, 0, 0],
        distx="normal",
        dx=dx_sigma,
        disty=None,
        dy=0.,
        distz="normal",
        dz=dz_sigma, 
        distxprime="none",
        dxprime=dxprime_sigma,
        distzprime="none", 
        dzprime=dzprime_sigma,
        distE='normal', 
        energies=[Ec, Esigma],
        polarization='h',
        nrays=nrays)
```

I have added three monitors along the beam path aiming to monitor the beam size along the propagation axis:
- Monitor1: 0mm, 
- Monitor2: 100mm 
- Monitor3: 1000mm
I am confused with the beam sizes that I monitor. I am expecting to see the beam size increase corresponding to a divergence of 2.51urad but instead they seem constant. 

![beamMonitor3_beamSize](https://user-images.githubusercontent.com/23210247/200868555-4527e066-4622-4093-aae4-856af847cdcd.png)
![beamMonitor2_beamSize](https://user-images.githubusercontent.com/23210247/200868560-40aef78e-3791-4e02-ae8d-1e3217c5b511.png)
![beamMonitor1_beamSize](https://user-images.githubusercontent.com/23210247/200868565-40edd571-7b54-4c72-b95b-666c01e34b65.png)

Can you help me understand what I am defining wrong? Is there perhaps a more proper way to do this?

Thank you for your time!
Best regards,
Myrto

// File attached below
[geometricSource_py.txt](https://github.com/kklmn/xrt/files/9972385/geometricSource_py.txt)

**Comment by emasimak** [comment]
HI! 
Thank you for your quick reply! 
... and thank you for pointing out this silly mistake! I would not have noticed it.
If I were to use None for the distributions of dxprime and dzprime however, wouldn't that mean that the divergence should remain constant through the beam propagation? My understanding is that dx,dz are the beam sizes and dxprime, dzprime the angular divergence in each of the axes. So a constant angular divergence of dxprime would affect the FWHM of the beam in x as: (FW' - FW)/(distance) = dxprime. I tried to use also "flat" but I had the same results in terms of beam size. 
I am misunderstanding something in the definition. If you can offer any advice it would be much appreciated.

**Comment by kklmn** [comment]
>If I were to use None for the distributions of dxprime and dzprime however, wouldn't that mean that the divergence should remain constant through the beam propagation?

Not just constant but zero. The size of None distribution is irrelevant. I don't see why a size parameter should define the central value. For the central x' and z' we have `yaw` and `pitch`.

> I tried to use also "flat" but I had the same results in terms of beam size.

Then something is wrong in your script again.

**Comment by kklmn** [comment]
If scripting is a problem, there are many ready examples to look at in 'examples' and 'tests'.
In particular, you may examine this one: `tests/raycing/test_param_mirror.py`.

**Comment by emasimak** [comment]
Hi!
I thought I had understood how the definition of dxprime, dzprime worked but apparently not.

I am attaching a sketch to explain what I want to define in the code.  
![beam](https://user-images.githubusercontent.com/23210247/202433699-d7eee9b1-7ba4-4784-b2d9-38c8c2ca9634.png)
On the left you see the beam that is defined through a GeometricSource when:
`       distx="normal",
        dx=Sx/2.355,
        disty=None,
        dy=0.,
        distz="normal",
        dz=Sy/2.355 `

One the right you see the divergence I want to include in the beam. I want to accomplish a beam size of:
Sx' = Sx + (θ * dist). 
I was expecting that if I define `distxprime='flat',
        dxprime=1e-3, 
        distzprime='flat', 
        dzprime=1e-3`
that θx (or 2θx) [rad] would be equal to dxprime (similarly for the zaxis) and that if I place a screen in 1m distance I would see an increase of Sx equal to 1mm. Instead I get the beam sizes shown in the picture below.

![beamPropagation1m](https://user-images.githubusercontent.com/23210247/202439171-1ad87f85-7c94-43d0-84ab-39221557f137.png)

It is not clear to me how I should define dxprime/dzprime to accomplish the beam divergence that I need.
Thank you in advance for your time!
/Myrto

// Used code:
[geometricSource_wOneCrystal-demo_py.txt](https://github.com/kklmn/xrt/files/10031175/geometricSource_wOneCrystal-demo_py.txt)

**Comment by kklmn** [comment]
Hi!

`distx` and `distxprime` are _independent_ distributions. In other words, in your picture of the red source spot, _each point_ has a random angular distribution `distxprime`, not that the top part will have positive inclinations.

What you describe as your expectation is a point source with a truncated tip, no idea why you want it truncated.

If you need a defined fan of rays then just define it as a point source. Then x and x' will be explicitly dependent.

**Comment by emasimak** [comment]
Hi! 
Thank you for quick and helpful clarification! I will keep it in mind.
I assume that as point source you refer to the MeshSource, right?

Thank you for your time!
Myrto

**Comment by emasimak** [comment]
Thank you!
