### ISSUE TITLE
run python script created in xrtQook, get different result in Pycharm

### ISSUE THREAD

**Issue by leahwang1962** [kklmn/xrt#133]
Hello,
I built a beamline and plots in xrtQook, and "generate python script", then "save python script and run", (assume I saved it as p1.py)I got correct results in xrtQook.
Then in Pycharm, I opened this p1.py and run it, however I got different(wrong) results.
Do you know the possible reasons? I am using Pycharm community Edition 2021.3.2
Thanks

**Comment by kklmn** [comment]
One possibility is that you're running two different versions of xrt. In PyCharm console import xrt and examine `xrt.__file__`.
