### ISSUE TITLE
Johannson focus beam plot 

### ISSUE THREAD

**Issue by leahwang1962** [kklmn/xrt#137]
Hello,
For Johansson crystal Si(111), if the point source dzprime=0, I got a plot of  Horizontal line at focus which I expect a point(in fact xrtGlow gives a point focus). However if I increase dzprime to a certain value like dzprime=0.001, the plot at focus will show a narrow vertical line which is correct.
Can you help me to understand why I got a horizontal line(instead of a focus point) at focus position when dzprime=0? Thanks.
![xrtGlow](https://user-images.githubusercontent.com/99756010/222516345-feef649f-795f-4e46-a71d-868bf1665eb2.jpg)
![pointSourcedzprime0](https://user-images.githubusercontent.com/99756010/222516373-b75b2c65-0d44-4f67-8aff-3224847135b1.png)
![pointSourcedzprimeNotZero](https://user-images.githubusercontent.com/99756010/222516393-a2b8c9fe-a8a9-405a-9024-4ec25c9b76e6.png)

**Comment by leahwang1962** [comment]
Thanks

**Comment by kklmn** [comment]
You may want to set your own limits for x-axis and then you will not get this surprising scaling from matplotlib.
