### ISSUE TITLE
xrtGlow not starting (OpenGL error)

### ISSUE THREAD

**Issue by maurov** [kklmn/xrt#14]
Hello,

I wanted to give a try to `xrtGlow` and I got the following OpenGL error when starting the 3D view from `xrtQook`. I have simply run the [xrtQook tutorial](http://xrt.readthedocs.io/qook_tutorial.html#qook-tutorial).

Here my system (**conda environment on a windows machine**):

- Windows-10
- Python 3.6.3
- Qt 5.6.2
- PyQt5 5.6
- pyopencl 2018.1.1
- OpenGL 3.1.1a1
- xrt 1.3.0beta (fetched from github today)

Here the trace:

```
(py36) C:\Users\rovezzi\local\xrt\xrt\gui>python xrtQookStart.pyw
Class crystalSi01 successfully initialized.
Class bendingMagnet01 successfully initialized.
Class oe01 successfully initialized.
Class screen01 successfully initialized.
Class crystalSi01 successfully initialized.
Class bendingMagnet01 successfully initialized.
Class oe01 successfully initialized.
Class screen01 successfully initialized.
25275 rays of 100000
50488 rays of 100000
75685 rays of 100000
100638 rays of 100000
OE1 pitch: 0.199049781904
Screen1 center: [0, 21000, 420.54685697964965]
Traceback (most recent call last):
  File "C:\Users\rovezzi\AppData\Local\conda\envs\py36\lib\site-packages\xrt\gui\xrtGlow\__init__.py", line 3285, in initializeGL
    gl.glutInit()
  File "C:\Users\rovezzi\AppData\Local\conda\envs\py36\lib\site-packages\OpenGL\GLUT\special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "C:\Users\rovezzi\AppData\Local\conda\envs\py36\lib\site-packages\OpenGL\platform\baseplatform.py", line 407, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
```
I know nothing about OpenGL, so any help is welcome.

Thanks,
Mauro

**Comment by yxrmz** [comment]
Hi,

It's a known bug, some pyopengl distributions are incomplete. I see, you are using Anaconda, so I'd recommend to uninstall the Anaconda-provided pyopengl and use the *.whl package from Gohlke, https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl

Regards,
Roman

**Comment by maurov** [comment]
@yxrmz Thanks for your help. I have pip-installed `pyopengl` and `pyopencl` from Gohlke within my Anaconda environment and it works now.
