### ISSUE TITLE
numpy.long(): gives error with numpy>=1.24 (Expired deprecation) 

### ISSUE THREAD

**Issue by schlepuetz** [kklmn/xrt#140]
With the release of numpy 1.24, the support for numpy.long() seems to have been dropped (deprecated since 1.20). 

For example, the following line gives me an error when running in an environment with numpy>=1.24:
https://github.com/kklmn/xrt/blob/8ec5e3153742fa9bd1c8d6f18b61e451da400c65/xrt/backends/raycing/sources_geoms.py#L221
The same thing works flawlessly with numpy=1.23.5, for example. 

Hopefully a small fix to keep things compatible with updated environments.

Many thanks for the great tool and the support!

**Comment by kklmn** [comment]
Hi!
Thank you for reporting the problem!
Please try the current GitHub version.

**Comment by schlepuetz** [comment]
Thanks a lot for the quick fix @kklmn!
