### ISSUE TITLE
Class bendingMagnet01 not initialized

### ISSUE THREAD

**Issue by CharlesCardot** [kklmn/xrt#141]
Hello,

I am a novice user attempting to get the GUI xrtQook up and running. My process:

pip install xrt
pip install PyQt5
pip install pyqtwebengine

I include the two extra dependencies because I could not get xrtQookStart.pyw to even run without them. Once this is all installed the GUI opens without issue, but once I try to add a bendingMagnet to the beamline I get this output:

```
(new) C:\Users\ccard\UW Seidler Research\Projects\pythonXRT\new\Scripts>python xrtQookStart.pyw
js: Uncaught ReferenceError: $ is not defined
js: Uncaught ReferenceError: $ is not defined
js: Uncaught ReferenceError: $ is not defined
C:\Users\ccard\UW Seidler Research\Projects\pythonXRT\new\lib\site-packages\xrt\backends\raycing\sources_sybase.py:127: FutureWarning: In the future `np.long` will be defined as the corresponding NumPy scalar.
  self.nrays = np.long(nrays)
Incorrect parameters. Class bendingMagnet01 not initialized.
Method shine() was added to bendingMagnet01
js: Uncaught ReferenceError: $ is not defined
```

When I add optics or screens, they all seem to be initialized without issue, but I can't initialize any of the sources without encountering this "Incorrect paramters. Class (...) not initialized"

**Comment by kklmn** [comment]
Hi!
Looks like a compatibility problem with numpy >= 1.24. I've fixed it and run a few examples.
Please try the current GitHub version and get back with the result (also tell your numpy version).
Thanks!

**Comment by CharlesCardot** [comment]
Awesome, will do! I should get a chance to run it later tonight or early on Monday.

**Comment by CharlesCardot** [comment]
Thank you, it seems fixed now! I was able to create a bending magnet object and visualize it with xrtGlow.
