### ISSUE TITLE
xrtGlowScreen OE Surface bug

### ISSUE THREAD

**Issue by CharlesCardot** [kklmn/xrt#142]
Hello,

I have been trying to follow the qook_tutorial (https://xrt.readthedocs.io/qook_tutorial.html) but I have been running into a visual bug when I include any optical element in my beamline.

Here are some images of the OE surface bug:
![xrtGlowOEvisualbug_1](https://user-images.githubusercontent.com/43706411/234064153-ca9e5044-2d06-45c6-9fe4-dca3e35cd225.png)
![xrtGlowOEvisualbug_2](https://user-images.githubusercontent.com/43706411/234064170-df844246-bd2e-4299-804d-3b1b7a843aea.png)

Here are the beamline.py and beamline.xml files generated using xrtQook 
[temp_beamline.zip](https://github.com/kklmn/xrt/files/11312884/temp_beamline.zip)

Here is the output from loading the beamline.xml file and opening it in xrtGlow:
```
C:\Users\ccard\UW Seidler Research\Projects\pythonXRT\xrt\build\scripts-3.10>python xrtQookStart.py
js: Uncaught ReferenceError: $ is not defined
js: Uncaught ReferenceError: $ is not defined
Class crystalSi01 successfully initialized.
Class bendingMagnet01 successfully initialized.
Class oe01 successfully initialized.
Class screen01 successfully initialized.
js: Uncaught ReferenceError: $ is not defined
Class crystalSi01 successfully initialized.
Class bendingMagnet01 successfully initialized.
Class oe01 successfully initialized.
Class screen01 successfully initialized.
25838 rays of 100000
51387 rays of 100000
77124 rays of 100000
102980 rays of 100000
OE1 pitch: 0.1990495872675595
Screen1 center: [0, 21000, 420.5362721950768]
Screen1 center: [0, 21000, 420.5362720819875]
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
```

I also tested this with a Johann cylinder element, and encountered the same issues when I turned the surface element on. I am not certain if this bug is only visual, or if there is some other underlying issue.

My process for installation:
```
git clone https://github.com/kklmn/xrt
python setup.py install
pip install PyQt5
pip install pyqtwebengine
```

For xrtGlow, you need OpenGL, so I installed the appropriate .whl of PyOpenGL for my system and Python version 
PyOpenGL-3.1.6-cp310-cp310-win_amd64, acquired from, https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl

**Comment by kklmn** [comment]
Hi!

I can't reproduce this. So far, no ideas.
Please paste here what you see under "Your system:" on the welcome page of xrtQook.

`js: Uncaught ReferenceError: $ is not defined` is due to an old version of Sphinx and absent `sphinxcontrib-jquery`.

**Comment by CharlesCardot** [comment]
![xrtGlowOEvisualbug_3](https://user-images.githubusercontent.com/43706411/234106921-1ff3bf24-8c6e-48ba-ac64-68b32ff01ab6.png)

**Comment by kklmn** [comment]
I see that you're not running xrtQook from the last GitHub version, whereas I guess you do have it. Please try to locate the new version of xrtQookStart.py and start it from that location.

**Comment by CharlesCardot** [comment]
Hello,

You were right! Sadly the rabbit hole goes deeper. I suspected that somehow my "xrt" library wasn't pointing at the one that I downloaded from github and was instead pointing at the one I took from PyPi, so I created an entirely new python environment and installed everything from scratch. I recloned the github repo, reran `setup.py` using the new python envrionment. I navigated to `xrt\xrt\gui` and ran `python xrtQookStart.py`.

This was the output

```
(new_envrionment) C:\Users\ccard\Downloads\xrt\xrt>cd gui

(new_envrionment) C:\Users\ccard\Downloads\xrt\xrt\gui>python xrtQookStart.py
[21396:18996:0424/135547.230:ERROR:cache_util_win.cc(21)] Unable to move the cache: Access is denied. (0x5)
[21396:18996:0424/135547.230:ERROR:cache_util.cc(139)] Unable to move cache folder C:\Users\ccard\AppData\Local\python\QtWebEngine\Default\GPUCache to C:\Users\ccard\AppData\Local\python\QtWebEngine\Default\old_GPUCache_000
[21396:18996:0424/135547.231:ERROR:disk_cache.cc(184)] Unable to create cache
[21396:18996:0424/135547.231:ERROR:shader_disk_cache.cc(606)] Shader Cache Creation failed: -2
Traceback (most recent call last):
  File "C:\Users\ccard\Downloads\new_envrionment\lib\site-packages\sphinx-6.2.0-py3.10.egg\sphinx\registry.py", line 442, in load_extension
    mod = import_module(extname)
  File "C:\Users\ccard\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sphinxcontrib.applehelp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ccard\Downloads\new_envrionment\lib\site-packages\xrt-1.5.0-py3.10.egg\xrt\gui\xrtQook\__init__.py", line 163, in render
    ext.sphinxify(self.doc, cntx, img_path=self.img_path)
  File "C:\Users\ccard\Downloads\new_envrionment\lib\site-packages\xrt-1.5.0-py3.10.egg\xrt\gui\commons\ext.py", line 115, in sphinxify
    sphinx_app = Sphinx(srcdir, DOCDIR, DOCDIR, doctreedir, buildername,
  File "C:\Users\ccard\Downloads\new_envrionment\lib\site-packages\sphinx-6.2.0-py3.10.egg\sphinx\application.py", line 225, in __init__
    self.setup_extension(extension)
  File "C:\Users\ccard\Downloads\new_envrionment\lib\site-packages\sphinx-6.2.0-py3.10.egg\sphinx\application.py", line 404, in setup_extension
    self.registry.load_extension(self, extname)
  File "C:\Users\ccard\Downloads\new_envrionment\lib\site-packages\sphinx-6.2.0-py3.10.egg\sphinx\registry.py", line 445, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib.applehelp (exception: No module named 'sphinxcontrib.applehelp')

(new_envrionment) C:\Users\ccard\Downloads\xrt\xrt\gui>
```

The xrtQook window opens briefly before closing out. The same behavior is observed whether I run `python xrtQookStart.py` or `python xrtQookStart.pyw`.

It seems there is some issues with sphinx and now I can't even get the program to open.

**Comment by kklmn** [comment]
please try 
```
pip install sphinx=5.3.0
pip install sphinxcontrib-jquery
```

**Comment by CharlesCardot** [comment]
Same issue sadly, it may be connected to https://github.com/sphinx-doc/sphinx/issues/11130

**Comment by yxrmz** [comment]
Have you tried installing sphinxcontrib-applehelp explicitly? https://pypi.org/project/sphinxcontrib-applehelp/

**Comment by yxrmz** [comment]
ok, I'll try to reproduce it. so, it's anaconda, python 3.10 as a new environment, and no packages besides those suggested by xrt setup.py, right? what IDE do you use?

**Comment by CharlesCardot** [comment]
I tested it both with python's built in environment manager https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/, `python -m venv new_environment` and anaconda. Using python 3.10, no packages other than that from setup.py in xrt, PyQt5, pywebengine, and PyOpenGL. I usually use vscode as my IDE but I haven't been trying to get xrtQook to run in it, I've just been doing everything from command line.

I'm also on windows machine if that's relevant.

**Comment by yxrmz** [comment]
I assume it's windows 11 then, since I'm having similar issues with OpenGL on 11, but not 10.

**Comment by CharlesCardot** [comment]
That is correct, windows 11

**Comment by yxrmz** [comment]
I mean visualization bug in W11.
Now, regarding sphinx, here's what worked for me:
Fresh conda env, xrt installed with setup.py

conda install pyqt
conda install sphinxcontrib-applehelp
conda install sphinxcontrib-htmlhelp
conda install sphinxcontrib-jquery -c conda-forge

then install pyopengl, pyopengl-accelerate from Gohlke's whl's. Qook should work fine. (Glow still has issues with surfaces, I'll try to figure out what's wrong here)

**Comment by yxrmz** [comment]
Visualization issue is most probably related to the legacy opengl code we use to plot surfaces. Shaders-based code works fine in W11 (also much faster) but at the moment only implemented for OEs and screens, no slits and sources. I can upload it into a separate branch if you are interested, but I can't promise any support on it until we complete some higher-priority updates.
![image](https://user-images.githubusercontent.com/3704556/234177564-4391e520-1572-444f-a2de-875988e5ef27.png)

**Comment by kklmn** [comment]
I can only advise using WinPython. On my Win10 and Win11 xrtQook runs in all versions of WinPython 3.10+, right from the box after doing `pip install sphinxcontrib-jquery`, no need for any other installation.

**Comment by CharlesCardot** [comment]
"_Now, regarding sphinx, here's what worked for me:
Fresh conda env, xrt installed with setup.py

conda install pyqt
conda install sphinxcontrib-applehelp
conda install sphinxcontrib-htmlhelp
conda install sphinxcontrib-jquery -c conda-forge

then install pyopengl, pyopengl-accelerate from Gohlke's whl's. Qook should work fine. (Glow still has issues with surfaces, I'll try to figure out what's wrong here)_"

These steps worked for me! No more sphinx issues. I have not heard of WinPython before, it sounds like I should give it a try.

As for the visualization bug, it isn't game breaking in terms of actually using xrt. I will stick with the version that has the bug and just try to work around it. I'll be excited to update though once you have everything working with shaders.

Thank you both @yxrmz and @kklmn for your help solving this issue, I really appreciated it.
