### ISSUE TITLE
No graphs in tutorial

### ISSUE THREAD

**Issue by engd-ddev** [kklmn/xrt#144]
Hello,

Both myself and a friend of mine are unable to get graphs plotted on our separate pcs and it is our first times trying to set up xrt.

I am running it on Spyder and running with an external console. Currently, when I run the entire tutorial, it can produce the xrtGlow pathways, but the graph window pops up and then closes with the following error:

![image](https://github.com/kklmn/xrt/assets/109749970/6a3ebb59-940e-4aa0-b617-f61472713e3a)

I previously had an issue where I was not running it in an external terminal and got no graph window popup at all. 

Hope you can help

My version packages are:
![image](https://github.com/kklmn/xrt/assets/109749970/eabf223a-3f7f-4783-b40d-10d47df0eb3a)

N.B. I am on Windows 11, not 10.

**Comment by kklmn** [comment]
Hi,
what is your matplotlib version?

**Comment by kklmn** [comment]
Hi,
Thanks for reporting it!
In matplotlib >= 3.7, Axes.lines object of type ArtistList (damn, "list"!) has started behaving as a tuple. 
I've changed the deletion as [here](https://github.com/kklmn/xrt/commit/94925133c5a218931fe3572dce1526a45924f8fe).
Please update the whole xrt or just xrt/plotter.py, run your example and report back.

**Comment by engd-ddev** [comment]
Hi kklmn,

It worked perfectly! thanks for your help
