### ISSUE TITLE
Surface roughness on full-cylinder curved crystal

### ISSUE THREAD

**Issue by bbazi** [kklmn/xrt#146]
Hi,

I would like to implement surface roughness on a full-cylinder curved crystal, if I understand correctly one has to use the local_r_distorted and local_n_distorted functions to alter the the surface normals. See here below my attempt of introducing a radius range of 10 micrometer and a random pitch and roll rotation between 0 degrees and 0.01 degrees.

`class Cylinder(roes.SurfaceOfRevolution):

    def __init__(self, *args, **kwargs):
        self.r = kwargs.pop('r')
        super(Cylinder, self).__init__(*args, **kwargs)

    def local_r(self, s, phi):
        return self.r * np.ones_like(s)

    def local_n(self, s, phi):
        a = -np.sin(phi)
        b = np.zeros_like(s)
        c = -np.cos(phi)
        return a, b, c

    def local_r_distorted(self, s, phi):
        rng = np.random.default_rng()
        radius_distortion = 0.005 #[mm]
        r = rng.uniform(low=self.r - radius_distortion, high=self.r + radius_distortion, size=s)
        return r

    def local_n_distorted(self, s, phi):
        rng = np.random.default_rng()
        rotation_distortion = 0.01 * np.pi/180 #[rad]
        Rx = rng.uniform(low=0., high=rotation_distortion, size=s)
        Ry = rng.uniform(low=0., high=rotation_distortion, size=s)
        return (Rx, Ry)
`  
Does this surface roughness implementation seem okay or am I misinterpreting the use of the code? Thanks for your time.

Best, Benjamin

**Comment by kklmn** [comment]
Hi,

The uniform distribution looks strange to me in this context. Defining constants inside methods is not elegant, move them to init.

I would define roughness this way:

```
    def local_r_distorted(self, s, phi):
        return np.random.normal(0, self.roughness, len(s))
        
    def local_n_distorted(self, s, phi):
        a = self.local_r_distorted(s, phi)
        b = self.local_r_distorted(s, phi)
        over = self.roughness_corr_length
        # over = np.random.poisson(self.roughness_corr_length, len(s))  # try this as well
        return a/over, b/over
```

Good luck!

**Comment by bbazi** [comment]
Hi, 

Thanks for the adjustment!
I don't fully understand yet the roughness correction length constant, does this reflect a physical parameter of the crystal?

Best,
Benjamin

**Comment by kklmn** [comment]
This is "correlation length", it depends on the polishing process and is typically given by metrology.

**Comment by bbazi** [comment]
Okay, I understand now, many thanks!
