### ISSUE TITLE
A bug with aperture exception handling block

### ISSUE THREAD

**Issue by saga111a** [kklmn/xrt#150]
When we use a small aperture sometimes we have IndexError.
![IMG_20230815_073205-2](https://github.com/kklmn/xrt/assets/20823297/2a9c2c5b-30d0-43ae-8da3-e0edaebb7a53)

It's seems look like IndexError forgotten in exception handling block
![img-2023-08-15-15-48-35](https://github.com/kklmn/xrt/assets/20823297/2b059820-143d-4e0f-a787-50e1025dd0a4)
perhaps it should be like this?
```
except (ValueError, IndexError):
            self.spotLimits = []
```

**Comment by kklmn** [comment]
I wonder why this happens. Is it when all rays are bad?
Can you please insert `print(goodN.sum())` right after `goodN = lo.state > 0`?

**Comment by kklmn** [comment]
Do you change aperture's `spotLimits` in your script?

**Comment by saga111a** [comment]
I did not change SpotLimits (as I understand it). This bug has happened a few times, but it's a floating bug. I launched scripts with additional output, I hope tomorrow I will see an error and data output
block with changeble aperture:
```
    BL_NSU.WB_SLITS_20m = rapts.RectangularAperture(
        bl=BL_NSU,
        name=None,
        center=[0, 20000, 0],
        opening=[-8, 8, SLIT_DOWN, SLIT_UP])
```
( I don't think it matters, but here is some more information.
 I launch scripts by master python process and pass args to slave scripts and  thus the variables like SLIT_DOWN are set. Slit changes from -0.0005, 0.0005 to -0.1 0.1
```
        cmd = [interpretator, run_file, args]
        process = subprocess.Popen(cmd)
        process.wait()
```
)

**Comment by saga111a** [comment]
sorry for the long silence
I can't reproduce the error when using additional print. I removed all changes and got it. I will try more with print. May be it's a bug in python interpreter.
![Error](https://github.com/kklmn/xrt/assets/20823297/6a89d269-e27b-4904-9f45-d2b1da735d43)

**Comment by kklmn** [comment]
Do you run the script in several parallel processes?

**Comment by saga111a** [comment]
No, only one script per time.
Master process run xrt script with args,  when it finished next xrt script is runned by master.
Parallel execution only within xrt by  `threads=4, processes=4`

I have now removed the entry to the file and am using stdout to the file
python batch.py >> error.log 
I hope it can help reproduce error with logging

**Comment by kklmn** [comment]
please try this single assignment instead of assigning the list elements:
```
                self.spotLimits = [min(self.spotLimits[0], lo.x[goodN].min()),
                                   max(self.spotLimits[1], lo.x[goodN].max()),
                                   min(self.spotLimits[2], lo.z[goodN].min()),
                                   max(self.spotLimits[3], lo.z[goodN].max())]
```

**Comment by saga111a** [comment]
> I hope it can help reproduce error with logging

Nope, Script finished successfully =(

> please try this single assignment instead of assigning the list elements:

Ok, I will do

**Comment by saga111a** [comment]
I used these assignments and there was no error. Today in another pc(ubuntu server, XRT without changes) I have similar error
![ERROR_CLUSTER](https://github.com/kklmn/xrt/assets/20823297/90ee7626-c1b0-4473-8f60-3640eb0de769)
I changed the assignment and restarted. If there will no error, then the fix works.

**Comment by saga111a** [comment]
On long runs, this error to occur. I have encountered this error three times since the assignment change. When I use short run calculations I have never seen this.

changes and error 24.08
![ERROR_CLUSTER2](https://github.com/kklmn/xrt/assets/20823297/d0018666-b912-481d-809c-1798c21f178a)

error 29.08 - independency runs on two PC
![ERROR_CLUSTER3](https://github.com/kklmn/xrt/assets/20823297/345b5258-aac9-42de-b7e6-053993b26818)
![ERROR_CLUSTER4](https://github.com/kklmn/xrt/assets/20823297/1b02bae2-d72f-446f-9b8b-e2d5fccb03db)

Previously I was using Win PC and there was the error, after that I changed the OS. I thought it was in the work of the MS OS

**Comment by kklmn** [comment]
Thank you @saga111a for testing!
I have modified `apertures.py` again, and this time I believe it is bulletproof (thread-safe).
You can get the module from this GH repository.

**Comment by saga111a** [comment]
Ok I will try to use it now

**Comment by saga111a** [comment]
I tested 6 hour calc run. As expected no error, default values in spotlimits work. Issue should be closed?
