### ISSUE TITLE
Qt platform

### ISSUE THREAD

**Issue by y19880621** [kklmn/xrt#16]
Just now, I installed the newest XRT version on a my new computer( Windows 10 system, without Qt). When I tried  xrtQookStart.pyw, it reported an error : This application failed to start because it could not find or load the Qt platform plugin "windows" in "".  I checked the problem on the website. It seems that the problem can be solved by packaging the "..../Qt/..../plugins/platforms" folder with XRT. Does it correct, or should I have to install Qt? Thank you.

**Comment by y19880621** [comment]
I have installed Qt, but still it reports as follows:

This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".
Available platform plugins are: minimal, offscreen, windows.
Reinstalling the application may fix this problem.

**Comment by yxrmz** [comment]
Hi,
I would recommend to install the appropriate wheel package for your platform from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4

**Comment by kklmn** [comment]
Please give the complete terminal output including the start command.

**Comment by y19880621** [comment]
> C:\GitHub\XRT\xrt\gui>python xrtQookStart.pyw
> This application failed to start because it could not find or load the Qt platform plugin "windows"
> in "".
> 
> Available platform plugins are: minimal, offscreen, windows.
> 
> Reinstalling the application may fix this problem.

**Comment by kklmn** [comment]
please also give the result of

    from distutils.sysconfig import get_python_lib
    print(get_python_lib())

**Comment by kklmn** [comment]
what do you get when running C:\Anaconda2\Scripts\spyder.exe ?
- Spyder also uses PyQt.

**Comment by kklmn** [comment]
I guess you have another installation of python that is set default to Windows. Either try to fix the paths or at the installation time of anaconda you can select "make it default".
BTW, the python2 brunch is getting outdated. Unless you have solid grounds on continuing with it, I would suggest going to python3.

**Comment by y19880621** [comment]
Alright, thanks.

**Comment by yxrmz** [comment]
I believe, if you run the xrtQookStart.pyw from spyder (the one that works), qt would work as well.

**Comment by y19880621** [comment]
Other problems occurs ... 

1.  I am sure I have installed pyopencl. But XRT cannot recognize it. 

> C:\Users\Yiming>pip show pyopencl
> Name: pyopencl
> Version: 2018.1.1+cl21
> Summary: Python wrapper for OpenCL
> Home-page: http://mathema.tician.de/software/pyopencl
> Author: Andreas Kloeckner
> Author-email: inform@tiker.net
> License: MIT
> Location: c:\python36\lib\site-packages
> Requires: numpy, appdirs, cffi, pytools, decorator, pytest, six

![opencl](https://user-images.githubusercontent.com/18696534/38534121-0e563c34-3caf-11e8-9f07-c15d592190d2.png)

2.  Then I decided to use XRT without opencl. However, no matter how to set the "targetOpenCL" = "None/Auto", the following error occurs:

```
Starting Undulator.py


Press Ctrl+X to terminate process


pyopencl is not available!
dx = 0.008774964387392122 mm
dz = 0.002285825890132492 mm
dxprime = 3.1339158526400436e-06 rad
dzprime = 1.2030662579644695e-06 rad
K = 1.3099465008739157
E1 = 9999.999932617287
E3 = 29999.999797851862
B0 = 0.762561531841397
Traceback (most recent call last):
  File "D:/OneDrive/Codes/XRT/NanoProbeBeamlineTest/V4/Undulator/Undulator.py", line 137, in <module>
    main()
  File "D:/OneDrive/Codes/XRT/NanoProbeBeamlineTest/V4/Undulator/Undulator.py", line 123, in main
    NanoProbeTest = build_beamline()
  File "D:/OneDrive/Codes/XRT/NanoProbeBeamlineTest/V4/Undulator/Undulator.py", line 58, in build_beamline
    gp=0.001)
  File "C:\Python36\lib\site-packages\xrt\backends\raycing\sources_synchr.py", line 1017, in __init__
    self.reset()
  File "C:\Python36\lib\site-packages\xrt\backends\raycing\sources_synchr.py", line 1137, in reset
    self.E_max, self.Theta_max, self.Psi_max)[0]
  File "C:\Python36\lib\site-packages\xrt\backends\raycing\sources_synchr.py", line 1492, in build_I_map
    return self._build_I_map_conv(w, ddtheta, ddpsi, harmonic, dg)
  File "C:\Python36\lib\site-packages\xrt\backends\raycing\sources_synchr.py", line 1509, in _build_I_map_conv
    gamma = gamma * np.ones(NRAYS, dtype=self.cl_precisionF)
AttributeError: 'Undulator' object has no attribute 'cl_precisionF'
```

After modifing the code from `gamma = gamma * np.ones(NRAYS, dtype=self.cl_precisionF)` to `gamma = gamma * np.ones(NRAYS)`, the program can run properly, but really slow without opencl.

**Comment by yxrmz** [comment]
Well, _cl_precision_ in a conventional method really looks like a bug, thanks. 
Regarding the opencl, what's your target device, do you have the driver installed?

**Comment by y19880621** [comment]
My device is : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz.
I have installed the Intel SKD for OpenCL and the driver. 
A possible issue is that the operating system(win 10) was just upgraded automatically the day before yesterday. Maybe the driver cannot support the newest win 10 ?
Below is a screenshot of installed program from control panel.
![image](https://user-images.githubusercontent.com/18696534/38535565-a1673ff8-3cb6-11e8-81ec-f2f1f7771fca.png)

**Comment by y19880621** [comment]
Hi. The problem was solved by update the GPU driver rather than the CPU driver. Right now, everything works fine. I am really appreciate your help.
