### ISSUE TITLE
Python created from XRTGlow show different results

### ISSUE THREAD

**Issue by leahwang1962** [kklmn/xrt#161]
Hi, 
In XRTQook,  I created a spherical cylindrical mirror based on elliptical mirror. After building the beamline with source, mirror and screen, I run XRTGlow and got plot on the screen(a straight line alone X axis). Then I generated python script based on the exact same beamline, and run it, but I got different plot results( a broken line along X axis).  Do You know what is the cause?
Thanks a lot. 
[Spherical.zip](https://github.com/kklmn/xrt/files/13207932/Spherical.zip)
<img width="621" alt="XRTGlow" src="https://github.com/kklmn/xrt/assets/99756010/5a4e9630-db43-4b8c-b5a7-6bda51828bf1">
![plot01](https://github.com/kklmn/xrt/assets/99756010/5f0c3ca8-f7df-487d-aa8b-9df91bc722e0)

**Comment by leahwang1962** [comment]
Here is the python script  generated in XRTQook based on the above beamline.

[Spherical Cylinder.zip](https://github.com/kklmn/xrt/files/13208045/Spherical.Cylinder.zip)

**Comment by yxrmz** [comment]
At first glance Z and Y axes in Glow are have different scales, roughly 1:10, while histogram plot has an aspect rate of 1:1, so you have a 1-bin wide line in vertical dimension. Try adding _aspect_='auto' to the plot init code.

**Comment by leahwang1962** [comment]
seems not help. 
![image](https://github.com/kklmn/xrt/assets/99756010/c5911f4b-33e0-4072-9fa7-d41d719d9ec3)
![plot01_aspect_auto](https://github.com/kklmn/xrt/assets/99756010/421f5422-df50-43a8-a3bf-4df617a6a0f7)

**Comment by yxrmz** [comment]
1. The vertical size and vertical divergence of the beam are zero, so it's an infinitely narrow line - exactly what you see on the screen. You should set some finite values for dz and/or dzprime.
2. You are plotting the global beam coming out of the mirror, I would assume you want to see what's on your screen. Change the beam in the plot to 'screen01beamLocal01'

**Comment by kklmn** [comment]
Notice the scaling factor "1e-14" under "Φ". All your vertical coordinates are essentially zeroes.

**Comment by leahwang1962** [comment]
Got it. Thanks.
