### ISSUE TITLE
xyz_to_param and param_to_xyz for class ParabolicalMirrorParam

### ISSUE THREAD

**Issue by leahwang1962** [kklmn/xrt#171]
Hi,
Don't understand why there is no def xyz_to_param and param_to_xyz for class ParabolicalMirrorParam in xrt/backends/raycing/oes.py as there are one for class EllipticalMirrorParam.
Thanks for explanation.
Li

**Comment by kklmn** [comment]
`EllipticalMirrorParam` is parental to `ParabolicalMirrorParam`, so these methods are present in both classes.

**Comment by leahwang1962** [comment]
Oh thanks.
Sorry I didn't pay attention to the ParabolicalMirrorParam class def parameter.
