### ISSUE TITLE
How to simulate nested shells

### ISSUE THREAD

**Issue by NolannR** [kklmn/xrt#172]
Hello, 

I want to simulate a nested shell. My optical system consists of 2 cylinders in a conical approximation (the radius changes along the axis), the class I use for it is the following one:

class ConicalShells(roes.SurfaceOfRevolution):
    def __init__(self, *args, **kwargs):
        self.Rstart = kwargs.pop('Rstart')
        self.Rend = kwargs.pop('Rend')
        super(ConicalShells, self).__init__(*args, **kwargs)
    
    def xyz_to_param(self, x, y, z):
        phi = np.arctan2(x, z)
        return y, phi, np.sqrt(x**2 + z**2)

    def param_to_xyz(self, s, phi, r):
        return r * np.sin(phi), s, r * np.cos(phi)
    
    def local_r(self, s, phi):
        r = (self.Rstart * (0.5 - s / L) + self.Rend * (0.5 + s / L))
        return r

    def local_n(self, s, phi):
        slope = np.arctan(((np.array(self.Rend) - np.array(self.Rstart)) / L))
        
        a = -np.sin(phi)
        b = + slope
        c = -np.cos(phi)
        
        norm = np.sqrt(a**2 + b**2 + c**2)
        return a / norm, b / norm, c / norm

it works well and I obtain the expected result.

But now, I want to stack many cylinders to see the result when they are combined. From what I have now, I don't get the correct result in the detector plane.

Do you have any solution to do that? 

Thank you in advance for your answer.

NB: I leave you some images so you get a better understanding of my problem.

With one conical shell:
![Screenshot 2024-03-18 150024](https://github.com/kklmn/xrt/assets/67743260/2766678f-1778-4a14-9c6e-583d48e275a6)

With many shells simulated using many beamlines:
![Screenshot 2024-03-20 124329](https://github.com/kklmn/xrt/assets/67743260/e3634b60-b988-422c-a52f-8b9a51631a80)

The result I obtained with the class I implemented for simulating the nested shell using one beamline (for the first and last shell):
![image](https://github.com/kklmn/xrt/assets/67743260/a12a39e6-7990-40a4-b290-2a26daabab1b)

The result I obtained when I used all the nested shells:
![image](https://github.com/kklmn/xrt/assets/67743260/4c223258-5239-49b5-a6fd-d543b298b1ab)

Thank you for your help.

**Comment by NolannR** [comment]
Hi, 
I was thinking of a parallel stacking. Indeed, I was able to obtain what I wanted with the 'Polycapillary' code. 
Thank you.

**Comment by NolannR** [comment]
Hi,

I have a problem actually when I increase the number of shells. I see all of them when looking at the first mirror, but when looking at the second mirror, they disappear if I add too many of them.

![Screenshot 2024-03-25 143714](https://github.com/kklmn/xrt/assets/67743260/94bb00eb-beee-4c71-92d4-7b964bbb4cae)

when I add all of them (around 20), I see only the upper mirror for mirror 2 (I still see all of them for mirror 1).
![Screenshot 2024-03-27 124511](https://github.com/kklmn/xrt/assets/67743260/1261dddc-7ab7-429f-96ee-fee0da87997c)

I also have a problem when I want to see the result with GUI if I have more than 2 shells.

"
beamDict[gBeamName] = self.beamsDict[gBeamName]
KeyError: 'beamTmp'
"

Thank you for your help,

**Comment by NolannR** [comment]
Hi, 

Concerning the problem with GUI, I found a solution to visualize it.

Concerning the first part, I don't understand why the copy_beam isn't working for the mirrors2 for all the shells. It works well for mirrors1 (We can see all the shells), but it is not the case for mirrors2. When I increase the number of shells, they disappear and we only see the last one.

Due to the geometry, we can have overlapping in the raytracing result, (let's say a shell covers a range from 100 to 105 mm, the second one can cover a range from 102 to 107 mm). Does this induce problems in the copy_beam method? If so, do you have any advice to fix this problem?
Thank you.

**Comment by kklmn** [comment]
Hi,

Your last post is readable but I can't decipher any meaning from it. I'm not a mind reader.

**Comment by NolannR** [comment]
Hi,

My system consists of two shells. Each of them has a slope. So we have four points, R1, R2, R3, R4. The first shell starts at R1 and ends at R2, and the second shell starts at R3 and ends at R4.

It is a conical approximation, so the slope for R3-R4 is three times larger. Due to that, we can have overlapping when looking at an xrt result. Here's a simple sketch of what I mean by overlapping:
![image](https://github.com/kklmn/xrt/assets/67743260/d2cfa1e5-9cf8-407f-a6d2-0ff36c084206)

When I run the code to see the total result, I have what I showed you earlier. The shells on M1 are visible because there is still sufficient spacing between the shells, so no overlapping.
![image](https://github.com/kklmn/xrt/assets/67743260/cb283518-9e2b-400e-9e18-8c8838d834a7)

Here I simulated the result for two shells at a certain position, for M2.
![15](https://github.com/kklmn/xrt/assets/67743260/1a4b6587-4519-4806-8d25-2eb4505c1cce)
![14](https://github.com/kklmn/xrt/assets/67743260/a455ba5f-40ff-49ad-9083-cec91068957a)
![13](https://github.com/kklmn/xrt/assets/67743260/0e9ee786-eef4-4ff0-b294-c0c9c6bc5589)

So indeed, we see a ring disappearing due to overlapping between two shells, and this is the origin of my problem. My question is, since the copy_beam method doesn't fix this problem, do you have any suggestions to overcome this issue?

**Comment by kklmn** [comment]
It's still a maze of words. "My system consists of two shells" - ok; "The shells on M1" - what?! There is something bigger than "system"?
And you insist on posting no code.
Good luck in your quest!

**Comment by NolannR** [comment]
I apologize if I made it unclear. I thought the sketch I sent was enough to understand the origin of the problem. 

Anyway, I found a solution. Reversing the sum of each shell in run_process in the loop was enough.

"for (i, shell1), (j, shell2) in zip(reversed(list(enumerate(beamLine.M1))), reversed(list(enumerate(beamLine.M2)))):"
