### ISSUE TITLE
Problems generating code from materials

### ISSUE THREAD

**Issue by r1ckdu** [kklmn/xrt#180]
Hej fran Sverige,

I have just tried to make a beamline with materials from the predefined data in xrt using xrtqook it looks like so in the saved xml:
```
	<boronCarbide01 type="value">
		<properties type="prop">
			<name type="param">B4C</name>
			<elements type="param">['B', 'C']</elements>
			<quantities type="param">[4.0, 1]</quantities>
			<rho type="param">2.52</rho>
			<kind type="param">auto</kind>
			<t type="param">None</t>
			<table type="param">Chantler total</table>
			<efficiency type="param">None</efficiency>
			<efficiencyFile type="param">None</efficiencyFile>
			<refractiveIndex type="param">None</refractiveIndex>
		</properties>
		<_object type="object">xrt.backends.raycing.materials_compounds.BoronCarbide</_object>
	</boronCarbide01>
```

When I generate the code and run it it says it can't find rmats_compounds (same is true for rmats_elems). I can ofc insert that import myself ... but I guess that is not intended for a code generator.

How to fix this?
Windows 11, Python 3.9.19
Qt 5.15.8, PyQt5 5.15.9
OpenGL 3.1.6 but GLUT is not found
pyopencl 2024.2.2
Sphinx 7.3.7
xrt 1.6.0 in D:\\miniforge3\\envs\\xrt\\lib\\site-packages, this is the latest version on [PyPI](https://pypi.org/project/xrt)

Side note: I would love to see the beamline at work - is there a general troubleshooting page if GLUT is not found? I must have overlooked it or am the only person having issues with this?

**Comment by kklmn** [comment]
Hej,

Let's start with glut. If your problem with glut is the same as mine, OpenGL wants `freeglut64.vc14`. If you look in `your-python-path\Lib\site-packages\OpenGL\DLLS\` for it, you'll probably find `freeglut64.vc16`. Rename it (or copy) to `freeglut64.vc14` and start xrtQook again.

**Comment by r1ckdu** [comment]
Hm okay!
That seems different. In my case the OpenGL folder does not have a DLLS subfolder.
The freeglut I have installed (3.2.2) installs an application into my conda venv under
`{env-name}\Library\bin\freeglut.dll`

I have tried moving freeglut.dll to the DLLS folder and renamed as you suggest - same issue.

**Comment by kklmn** [comment]
In `..\site-packages\OpenGL\platform\ctypesloader.py` find `_loadLibraryWindows()` and insert print statements for `name` and `fullName`. The dll should either be in the search path or in 'DLLS' folder of OpenGL. I guess your `freeglut.dll` is in the search path but is named differently. I guess it should be named `freeglut64.vc14.dll` (check it with the prints), just make a copy with this name.

**Comment by kklmn** [comment]
Hej igen,

I've added a few import statements in the generated xrtQook code and pushed it to GitHub. This will be included in the next release, or you may want to use the current GitHub code.

Thank you for spotting the problem!

**Comment by r1ckdu** [comment]
@kklmn Happy that there seems to be a simple fix for the import issue. Ill just migrate to pull from github then. Tack!

I did make the print statements too. Renaming it to freeglut64.vc14 and keeping it in place was exactly the fix.

Really am enjoying the images now, Konstantin!

**Comment by r1ckdu** [comment]
Whoops. Not so fast.
Just pulling from git now made me se lots of issues with pyopencl.

Any reason that should happen?
```
Traceback (most recent call last):
  File "D:\miniforge3\envs\xrt\lib\site-packages\pyopencl\cache.py", line 495, in create_built_program_from_source_cached
    _create_built_program_from_source_cached(
  File "D:\miniforge3\envs\xrt\lib\site-packages\pyopencl\cache.py", line 417, in _create_built_program_from_source_cached
    prg.build(options_bytes, [devices[i] for i in to_be_built_indices])
  File "D:\miniforge3\envs\xrt\lib\site-packages\pyopencl\__init__.py", line 736, in program_build
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: INVALID_COMPILER_OPTIONS - clBuildProgram failed: INVALID_COMPILER_OPTIONS
```

**Comment by r1ckdu** [comment]
Ah - fixed myself. No one likes spaces in file names :)

You can't see it from here, but there was a different error message. I saw the spaces, renamed my base folder et voila.
