### ISSUE TITLE
VLS grating local_g direction

### ISSUE THREAD

**Issue by wholingfei** [kklmn/xrt#183]
Hi,

I'm wondering that could you pls provide the users some examples for defining the VLS grating? From your example code of constant line spacing grating, I assume the local_g should be along the negative direction of the y axis if it is a y grating. Thus, I set the gratingDensity attribute in the VLS grating to be negative. However, the "wrong coefficients: negative groove density" information pops out. 

May I ask that is it mandatory for the user to write a new local_g function to override the VLSGrating class? Perhaps I made something wrong. Could you please give us some description of the default definition of direction of vector local_g? 

Thanks.

**Comment by kklmn** [comment]
Hi!

You're right, we are mixing two things here that we shouldn't mix. One thing is to calculate groove positions and here we need positive increments (possibly variable), and the other thing is to calculate the grating vector **g** (also possibly variable). We should give the user the freedom to define the direction of **g** that depends on the user's definition of positive and negative orders.

I've removed the assertion for a positive increment and put an `abs()` there. I think the situation when **g** changes its sign is never possible.

The present GH code has this change.

**Comment by wholingfei** [comment]
Hi,

Thanks for your quick response! Now I think I understand.
