### ISSUE TITLE
Problem when using pytte and OpenCL for bent asymmetric Laue crystal

### ISSUE THREAD

**Issue by luweb** [kklmn/xrt#187]
Hello, I am trying to simulate spectrometer response using bent asymmetric Laue alpha-quartz 100. 

However, when  **useTT=True** and turn on targetOpenCL, I am not able to set repeats > 1. If I do that, xrt will run once and in the second run I get the following error:

> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\threading.py", line 1045, in _bootstrap_inner
>     self.run()
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\site-packages\xrt\multipro.py", line 265, in run
>     raycing_output = raycing.run.run_process(self.card.beamLine)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "c:\Users\goncalvesweb1\OneDrive - LLNL\Documents\Python Scripts\NSS_xrt.py", line 137, in run_process
>     bentLaueQuasiToroidbeamGlobal01, bentLaueQuasiToroidbeamLocal01 = beamLine.bentLaueQuasiToroid.reflect(
>                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\site-packages\xrt\backends\raycing\oes_base.py", line 1140, in reflect
>     self._reflect_local(good, lb, gb,
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\site-packages\xrt\backends\raycing\oes_base.py", line 2129, in _reflect_local
>     refl = matSur.get_amplitude_pytte(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\site-packages\xrt\backends\raycing\materials.py", line 1814, in get_amplitude_pytte
>     tminCL, tmaxCL = ucl.run_parallel(
>                      ^^^^^^^^^^^^^^^^^
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\site-packages\xrt\backends\raycing\myopencl.py", line 592, in run_parallel_desktop
>     kernel = getattr(self.cl_program[0], kernelName)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\site-packages\pyopencl\__init__.py", line 443, in __getattr__
>     knl = Kernel(self, attr)
>           ^^^^^^^^^^^^^^^^^^
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\site-packages\pyopencl\__init__.py", line 805, in kernel_init
>     self._setup(prg)
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\site-packages\pyopencl\__init__.py", line 811, in kernel__setup
>     self._enqueue, self._set_args = generate_enqueue_and_set_args(
>                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\site-packages\pyopencl\invoker.py", line 402, in generate_enqueue_and_set_args
>     pmod, enqueue_name = invoker_cache[cache_key]
>                          ~~~~~~~~~~~~~^^^^^^^^^^^
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\site-packages\pytools\persistent_dict.py", line 565, in __getitem__
>     return self.fetch(key)
>            ^^^^^^^^^^^^^^^
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\site-packages\pytools\persistent_dict.py", line 698, in fetch
>     stored_key, value = self._fetch(keyhash)
>                         ^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\site-packages\pytools\persistent_dict.py", line 687, in _fetch
>     c = self._exec_sql("SELECT key_value FROM dict WHERE keyhash=?",
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\site-packages\pytools\persistent_dict.py", line 526, in _exec_sql
>     return self._exec_sql_fn(lambda: self.conn.execute(*args))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\site-packages\pytools\persistent_dict.py", line 534, in _exec_sql_fn
>     return fn()
>            ^^^^
>   File "C:\Users\goncalvesweb1\AppData\Local\anaconda3\Lib\site-packages\pytools\persistent_dict.py", line 526, in <lambda>
>     return self._exec_sql_fn(lambda: self.conn.execute(*args))
>                                      ^^^^^^^^^^^^^^^^^^^^^^^^
> sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 7728 and this is thread id 18220.

Here I used my own OE child class, but I tried with bentLaue2D and got the same error.

**Comment by kklmn** [comment]
Hi,
About the sqlite3 error in pyopencl, something has changed in python 3.12 in threading. Not the new pyopencl is the culprit, I tried it with an older python, no error. I found the error about a week ago and fixed it by forcing no cache in pyopencl. The present GH version has the fix.

**Comment by luweb** [comment]
Perfect, it works now. Thank you so much!
