### ISSUE TITLE
Passing in_plane_rotation parameter to pytte

### ISSUE THREAD

**Issue by luweb** [kklmn/xrt#188]
Hello, I have been trying to pass in_plane_rotation parameter to TTcrystal class by hardcoding it inside the Crystal class.

In the set_OE_properties method I include:

        # Instantiating pytte TTCrystal to calculate displacement vectors
        ttcrystal_kwargs = {'crystal': classname,
                            'hkl': self.hkl,
                            'thickness': Quantity(thickness*1000, 'um'),
                            'debye_waller': 1,
                            'xrt_crystal': self,
                            'Rx': Quantity(Rmum, 'um'),
                            'Ry': Quantity(Rsum, 'um'),
                            'in_plane_rotation': Quantity(60, 'deg'),  # <--------------------------------------------------------
                            'asymmetry': Quantity(alpha, 'rad')}

However, the results aren't as expected so I suspect there is more to it. Could you please provide recommendation on how to accomplish this, or do you guys have plans to include in_plane_rotation in xrt?

Thanks!

**Comment by yxrmz** [comment]
Hi, I'm looking into this issue, my results for "vanilla" pytte and xrt implementation look similar (corrected for the slight angular shift due to the difference in the integration "zero").
Have you been using the _in_plane_rotation_ or _master_ branch? Could you specify other parameters you pass into the tt_crystal init?

**Comment by yxrmz** [comment]
Oooh, I see what may be the source of confusion here. If you run pyTTE examples and define R=Quantity(1, 'm') in the TTCrystal init, pyTTE sets _both_ meridional and sagittal radii to R. When we run the xrt calculator we set them individually, so if you want to compare against pytte, set both Rm and Rs in xrtBentXtal.

**Comment by luweb** [comment]
You are right, I think it works. Thank you!
