### ISSUE TITLE
Question about making dispersion plots

### ISSUE THREAD

**Issue by luweb** [kklmn/xrt#189]
Hello, I would like to make an Energy vs Y plot to see the dispersion in my spectrometer. While I can get histograms for Y and for Energies separately, the only way to get a relationship between both is through the RGB colors.
In other words, I can get plot.yaxis.total1D_RGB which is related to Energy, but is there a way to get the energy directly? I am looking for something like "plot.yaxis.total1D_avgEnergy".
Thank you for all your help so far.

**Comment by kklmn** [comment]
Hi,

Color can be misleading. Two rays with energies E-δE and E+δE coming to the same histogram bin would result in the same color and brightness as two rays of energy E. With our separation into 3 color channels we still can build good looking spatial histograms weighted with energy distribution. This is much better than doing a simple (one-channel) averaging. What you want to get is a full 3D block with 2D images stacked in a third (energy) dimension. Technically this is doable, just almost always, except in cases such as yours, one would need to reduce from 3D to 2D in post-processing to get the results usable. Anyways, we don't do 3D histogramming in xrt.

You can solve your problem by going strictly monochromatic and analyzing spatial distributions at energies of your choice.
