### ISSUE TITLE
Saving histogram data

### ISSUE THREAD

**Issue by redisgreen** [kklmn/xrt#191]
Hi, I'd like to save the histogram data as a .mat file. Right now, i'm using scipy.io.savemat in an afterScript and it's working fine.

However, i'd like to automate my simulations with different aperture sizes and I can't get it to work. I've tried to move the savemat function from an afterScript to a generator that changes the aperture size, computes the plot and saves the results in a file, but it's trying to save the results before even computing the plot ('XYCAxis' object has no attribute 'binCenters'). 

Any idea on how to do it nicely ?

Thanks in advance

**Comment by yxrmz** [comment]
Hi, have you tried setting the saveName for your plot with "*.mat" filename?

**Comment by yxrmz** [comment]
See here: https://xrt.readthedocs.io/plots.html#persistentname

**Comment by kklmn** [comment]
Hi,

You need to save your results _after_ `yield` in the generator. See an example [here](https://xrt.readthedocs.io/raycing.html#scriptingraycing).
