### ISSUE TITLE
build ellipsoidal mirror

### ISSUE THREAD

**Issue by leahwang1962** [kklmn/xrt#193]
![image](https://github.com/user-attachments/assets/83d045ad-a696-4800-817c-1fba71bb63fc)
 Hi,
Is it possible to build an ellipsoidal mirror like above, with Mirror surface has shape of
rotational ellipsoid? I tried EllipticalMirrorParam with isCylinder=false, but can only get part of the surface(the rotation around the major axis can't reach 360degree)
Thanks.

**Comment by kklmn** [comment]
Hi,

Indeed, `EllipticalMirrorParam` did not allow the top part. I have added a new parameter `isClosed`, see [here](https://xrt.readthedocs.io/raycing.html#xrt.backends.raycing.oes.EllipticalMirrorParam), that controls this behavior. 

We have another class for ellipsoidal closed shape, [`EllipsoidCapillaryMirror`](https://xrt.readthedocs.io/raycing.html#xrt.backends.raycing.oes.EllipsoidCapillaryMirror).

The two classes differ in the meaning of `center` and `pitch` parameters, as explained in the docs, but they give the same result.

Both classes are exemplified in a new test script `tests/raycing/test_ellipsoid_tube_mirror.py`.

Please update from GH.

**Comment by leahwang1962** [comment]
Thanks for the update.
After copy the new oes.py,  I can see isClosed as a parameter for xrt.backends.raycing.oes.EllipticalMirrorParam in XRTQook's document part, but it's not in the beamline pane after EllipticalMirror added. Do I miss more files? 
![image](https://github.com/user-attachments/assets/2b5a9433-d322-4a40-8a83-705f840a9945)

**Comment by kklmn** [comment]
Thank you for testing it also with xrtQook! This is fixed now.

**Comment by leahwang1962** [comment]
Thanks for the update. Now the ray tracing works as expected. 
It would be more beneficial if  xrtQook can show the whole optic surface.
![image](https://github.com/user-attachments/assets/aee4a907-0889-4eee-9a00-74d968bf2f6e)

**Comment by kklmn** [comment]
This is fixed now, please try again.

**Comment by leahwang1962** [comment]
Now the surface very strange. 
![image](https://github.com/user-attachments/assets/38a11ca9-c0ac-4b2b-ac82-a623670e8c49)

**Comment by kklmn** [comment]
Please go to `tests/raycing/test_ellipsoid_tube_mirror.py`, make `showIn3D = True` in it and run it. Do you see the mirror surface as a circle? You can make `tubeLengtgh = 10000` to better see the ellipsoid.

**Comment by leahwang1962** [comment]
In xrtQook after I changed the EllipticalMirrorParam shape from "round" to "rect" , the optic closed surface shows correctly. Not sure why "rect" is a right choice. I also tried "None", but the beamline propagation can't complete.
tests/raycing/test_ellipsoid_tube_mirror.py also works to show the surface circle when showIn3D = True
Thanks a lot for your help.

**Comment by kklmn** [comment]
The "round" shape makes a disk (or a coin), which makes no sense for a closed shape like a capillary. I've now modified xrtGlow to ignore this combination and updated the docstrings. You don't have to update, just don't use "round".
Thank you for spotting this corner case.

**Comment by leahwang1962** [comment]
Thanks.
