### ISSUE TITLE
Parameter setting of ellipsoid monocapillary

### ISSUE THREAD

**Issue by Z-zhq** [kklmn/xrt#198]
Hello, why does the ellipsoid capillary I set have a tail (highlighted in red)? Is there something wrong with my parameter settings? Also, I don't quite understand the meaning of limPhysY parameter. (I thought its first and second values represent the minimum and maximum values of the object on the Y-axis, but it doesn't seem to be the case from my graph.)
<img width="996" alt="屏幕截图 2024-09-02 175521" src="https://github.com/user-attachments/assets/e414e759-823d-4494-ba2a-37ae41e4c320">
<img width="974" alt="屏幕截图 2024-09-02 175536" src="https://github.com/user-attachments/assets/692f9165-61a8-48a1-b5e4-3b3d37228fb5">

my parameter:
limPhysX=[-1000, 300],
limPhysY=[-10, 300]

**Comment by kklmn** [comment]
Hi,
The ellipsoid length is controlled by `limPhysY`; the downstream end of it is set by `limPhysY[1]`.
For a closed surface, `limPhysX` becomes unnecessary. It can still have an effect if it is smaller than the radius of your ellipsoid.

**Comment by Z-zhq** [comment]
Sorry, I still don't understand, can you tell me what the length of the ellipsoid should be according to the parameters I set, i.e. limPhysY=[-10, 300], and how it is calculated?
Also how does limPhysY[1] control the downstream position, when I set it to 300 the downstream coordinates are not at y=300.
I would also like to know what is the meaning of the parameter center, if I set center=[0,150,0], how is “150” reflected in the space where the ellipsoid is located?

**Comment by kklmn** [comment]
`center` is a point in the global coordinate system. `limPhysY` are sizes measured from center. The length is limPhysY[1]-limPhysY[0].

**Comment by Z-zhq** [comment]
Thank you！I have another question, is the value “workingDistance” represented by W in the picture
![image](https://github.com/user-attachments/assets/b7b005a3-db11-4cb6-adf8-818b84da0d47)

**Comment by kklmn** [comment]
Yes, this is W.

**Comment by kklmn** [comment]
...Also I see that the drawing wrongly depicts the ellipse. It shouldn't go through foci.

**Comment by Z-zhq** [comment]
Yes, you're right. Thank you very much.
But why do I still not get a normal ellipsoidal capillary?
![image](https://github.com/user-attachments/assets/d2b48873-d346-412a-82c0-9bc63c76a0da)
![image](https://github.com/user-attachments/assets/3a476442-9a18-4b81-af04-70f3d226faee)

**Comment by Z-zhq** [comment]
Sorry, my question was too vague.
I did a simple test. The blue part of the graph is my capillary, which is in the middle of the whole ellipsoid. The exact parameters are labeled on the graph.
![image](https://github.com/user-attachments/assets/31444ed2-2966-4cee-bc25-ae00206b0025)
My simulation parameters are as follows：
       beamLine.ellipsoidCapillaryMirror01 = roes.EllipsoidCapillaryMirror(
        bl=beamLine,
        name=None,
        limPhysY=[3, 7],
        ellipseA=5,
        ellipseB=3,
        workingDistance=2)

I don't understand what went wrong, I still don't get the expected capillary

**Comment by Z-zhq** [comment]
I'm very sorry, my question was too vague.
I did a simple test. The blue part of the graph is my capillary, which is in the middle of the whole ellipsoid. The exact parameters are labeled on the graph.
![image](https://github.com/user-attachments/assets/664172f1-2de3-4e9b-80bd-8b1dcecc317f)

My simulation parameters are as follows：
    beamLine.ellipsoidCapillaryMirror01 = roes.EllipsoidCapillaryMirror(
        bl=beamLine,
        name=None,
        limPhysY=[3, 7],
        ellipseA=5,
        ellipseB=3,
        workingDistance=2)

I don't understand what went wrong, I still don't get the expected capillary. I would appreciate your help.
![image](https://github.com/user-attachments/assets/9feaf49c-f347-4b59-8d73-93f3d5f8b9c1)

**Comment by kklmn** [comment]
limPhysY=[-2, 2]
as measured from the "center" in local coordinates. You can search the documentation for "limPhysY" and find out what it is.

**Comment by Z-zhq** [comment]
I'm such a dummy, thanks for your patience! BTW, your software is superb!
