### ISSUE TITLE
EllipsoidCapillaryMirror can't bring rays into focus

### ISSUE THREAD

**Issue by Z-zhq** [kklmn/xrt#210]
Hi, I have tried to change the parameters in the program _test_ellipsoid_tube_mirror.py_ as per the sketch below, the changed parameters are:

E0, dE = 9000., 5.,
p = 4.
q = 4.
tubeLengtgh = 4.
tubeRadius = 3.  # at the topstream of the capillary
Mirror = roe.EllipsoidCapillaryMirror

![image](https://github.com/user-attachments/assets/67e04c51-ac3a-4a57-8bc9-cb74730a37f2)

However, the rays passing through the capillary ellipsoid mirror cannot be focused on the focal point of the ellipsoid as in the original example, which is where the screen is located in the following figure.

![image](https://github.com/user-attachments/assets/28353d27-4889-475d-af80-e13c0c83ff51)

What error did I make in the process? I need your designation and help very much.

**Comment by kklmn** [comment]
You're probably using an old version. Use the one from GitHub.
