### ISSUE TITLE
wave caculation and coherence analysis issue

### ISSUE THREAD

**Issue by goxrt** [kklmn/xrt#24]
Hi, I am now trying using the coherence analysis. The results seem to be different from the theoretical. In my simulaiton, I made following setting:
 
(1)    uniformRayDensity = True
   filamentBeam = True
(2) The wave generated by the source are directly projected on the screen:
            waveOnScreen = beamLine.fsmExp.prepare_wave(
            beamLine.source, beamLine.fsmExpX, beamLine.fsmExpZ)
            beamSource = beamLine.source.shine(wave = waveOnScreen, fixedEnergy=E0, withAmplitudes=True)
            outDict['beamFSMExp_{0:02d}'.format(ic)] = waveOnScreen      
(3) The field is computed following the exmaple of the XRT.
 
I don’t understand how the “Es = complexPlotPCAs.field3D” works, I tried to find this code in the source file but unsuccessfulll. Is the Es from the beamLine.source.shine for each repeat?
In addition, for the wave simulation, I really don’t catch the difference between the filamentBeam =true and false. Are they same if we have a very many repeats. Thanks

**Comment by kklmn** [comment]
plot.field3D is a stack of 2D fields per electron (repeat). It has a shape (repeats, nx, ny) and is supposed to be fed to [xrt.backends.raycing.coherence.calc_eigen_modes_PCA()](https://xrt.readthedocs.io/raycing.html#xrt.backends.raycing.coherence.calc_eigen_modes_PCA).

Filament beam is a single electron emission, where the electron has random lateral and angular shifts within the given emittance distributions ε<sub>x</sub> and ε<sub>z</sub> and an energy shift within the given energy spread. If filamentBeam == False, each ray in the beam has its own set of those random samples; you can't do wave propagation then. If you propagate in rays then yes, the results with and without filamentBeam will be equal at many repeats. 

Please also read the section [Coherence analysis and related plotting](https://xrt.readthedocs.io/raycing.html#module-xrt.backends.raycing.coherence). It refers to SoftiMAX examples and also to a test ...\tests\raycing\test_coherent_fraction_stack.py that you may want to scrutimnize.

**Comment by goxrt** [comment]
I got it, yes, I found that if the repeats is as large as enough, 1000 in my case. The coherence feature is same with the theoretical value. 
In addtion, I found some examples use a inner repeat inside the run_processm. For the filamentBeam, I found that only one spot source was shown for this series of repeated computation, eventhough I did not set accuBeam. I dont get the meanning of this inner-repeat, would you please comment it for me? thanks

**Comment by kklmn** [comment]
This is an attempt to optimize wave propagation. Frequently, only the last few diffraction events need more samples (repeats) whereas the intermediate wave distributions may remain at lower quality. By increasing the internal repeats and decreasing the global ones you may save some computation time with almost  the same quality at the final screen. In reality, this saving is little, so I typically go without internal repeats.

**Comment by goxrt** [comment]
thanks for your suggestion.
