### ISSUE TITLE
The verification of the wave propagation

### ISSUE THREAD

**Issue by goxrt** [kklmn/xrt#25]
Is there any examples about the verification of the wave propagation caculation, especially compared with SRW simulation or experiment? It is expected to carried out this work in our team, if it has been done, I would appreciate your comment on that work.

**Comment by kklmn** [comment]
To date, there are two verification tests:

1) A perfect comparison to analytic solutions with various types of Gaussian beam. [Here](https://xrt.readthedocs.io/test_waves.html#test-waves)

2) A beautiful match with experimental data from P10 at Petra3. [Here](https://xrt.readthedocs.io/gallery3.html#slit-diffraction-with-undulator-source)

There will be more experimental data coming from SoftiMAX and CoSAXS at MAX IV. Expected in late 2019.

We want to compare with SRW. I have no time for doing it myself. Maybe I will get a student for this. Or else a help from the community is welcome.
