### ISSUE TITLE
Coherent Fraction Reference

### ISSUE THREAD

**Issue by twguest** [kklmn/xrt#34]
Hi, 

I have a question regarding the formulation of the coherent fraction of a wavefront from the rms width of the intensity and DoC distributions. 

Explicitly, I am wondering if there are any references regarding the equation given here: https://xrt.readthedocs.io/raycing.html#coherence-signatures

Thanks,
T

**Comment by kklmn** [comment]
I've now added a reference there.

**Comment by twguest** [comment]
Thankyou
