### ISSUE TITLE
harmonic rejection caculation in ray tracing

### ISSUE THREAD

**Issue by goxrt** [kklmn/xrt#39]
Hi, I want to evaluate the harmonic rejection ratio in the ray tracing program. In this calculation, high harmonic photons are generated by the undulator, and the DCM works at low energy (for bragg-angle).  However, I found the **_rm.CrystalSi(hkl=(1, 1, 1))_** in DCM can not give the reflection for the high harmonic photons. I wonder if it is possible to perform this evaluation in this way. Thanks!
regards
Fugui

**Comment by yxrmz** [comment]
Hi, you'd have to use the CrystalHarmonics class, set Nmax to specify the number of harmonics to consider. I'd say, though, it's not especially efficient, a lot of rays would be rejected.

**Comment by kklmn** [comment]
Still with rm.CrystalSi, give the hkl=(3, 3, 3) or (4, 4, 4) or (5, 5, 5) etc.
CrystalHarmonics will give you all possible reflexes within a given range but, as Roman has said, with lower efficiency.

**Comment by goxrt** [comment]
thanks  for your suggestion!
