### ISSUE TITLE
DCM monochromatic flux vs. energy 

### ISSUE THREAD

**Issue by angelicacecilia** [kklmn/xrt#52]
Good morning,
I would like to plot the monochromatic flux  vs. Energy at the sample position, after the beam passes through a DCM.
with this script I can do it for a single energy, extracting the flux from the histogram. 
How can I do in a larger energy range?
Many thanks, Angelica

```

# -*- coding: utf-8 -*-
"""

__author__ = "Konstantin Klementiev", "Roman Chernikov"
__date__ = "2020-01-22"

Created with xrtQook


"""

import numpy as np
import sys
sys.path.append(r"/mnt/LSDF/anka-nc-cluster/home/ws/cc1372/.local/lib/python2.7/site-packages")
import xrt.backends.raycing.sources as rsources
import xrt.backends.raycing.screens as rscreens
import xrt.backends.raycing.materials as rmats
import xrt.backends.raycing.oes as roes
import xrt.backends.raycing.apertures as rapts
import xrt.backends.raycing.run as rrun
import xrt.backends.raycing as raycing
import xrt.plotter as xrtplot
import xrt.runner as xrtrun

CVD = rmats.Material(
    elements=r"C",
    kind=r"plate",
    rho=3.52,
    name=r"Diamond plate")

Si111 = rmats.CrystalSi(
    hkl=[1, 1, 1],
    name=r"Si111")

def build_beamline():
    P23_Main = raycing.BeamLine(
        alignE=10000)
 
    P23_Main.Undulator = rsources.Undulator(
        bl=P23_Main,
        name=r"P23",
        center=[0, 0, 0],
        eE=6.083,
        eSigmaX=156.1,
        eSigmaZ=6.9,
        eEpsilonX=1.2,
        eEpsilonZ=0.012,
        betaX=20.1,
        betaZ=3.97,
        distE=r"eV",
        eMin=4855,
        eMax=4866,
        nrays=10000,
        #xPrimeMax= 0.25,
        #zPrimeMax= 0.25,
        xPrimeMaxAutoReduce= False,
        zPrimeMaxAutoReduce = False,
        K=2.68,
        period=31.4,
        n=63)
  
    P23_Main.FEMask = rapts.RectangularAperture(
        bl=P23_Main,
        name=r"Frontend Mask",
        center=[0, 40000, 0],
        opening=[-12, 12, -5, 5])

    P23_Main.DiamondFilter = roes.Plate(
        bl=P23_Main,
        name=r"Diamond Filter",
        center=[0, 47600, 0],
        material=CVD,
        pitch=1.57079632679,
        limPhysX=[-5, 5],
        limOptX=[-5, 5],
        limPhysY=[-5, 5],
        limOptY=[-5, 5],
        t=0.05)

    P23_Main.SSRL_DCM = roes.DCM(
        bl=P23_Main,
        name=r"SSRL channel cut DCM",
        center=[0, 57000, r"auto"],
        bragg=[4861.64],
        material=Si111,
        material2=Si111,
        fixedOffset=20)
         
    P23_Main.SampleScreen = rscreens.Screen(
        bl=P23_Main,
        name=r"Sample",
        center=[0, 60000, r"auto"])

    return P23_Main

def run_process(P23_Main):
    UndulatorbeamGlobal01 = P23_Main.Undulator.shine()

    FEMaskbeamLocal01 = P23_Main.FEMask.propagate(
        beam=UndulatorbeamGlobal01)

    C_FilterbeamGlobal01, C_FilterbeamLocal101, CVDFilterAbsorbedPower = P23_Main.DiamondFilter.double_refract(
        beam=UndulatorbeamGlobal01,
        returnLocalAbsorbed=0)

    SSRL_DCMbeamGlobal01, SSRL_DCMbeamLocal101, SSRL_DCMbeamLocal201 = P23_Main.SSRL_DCM.double_reflect(
        beam=C_FilterbeamGlobal01)

    SampleScreenFootprint = P23_Main.SampleScreen.expose(
        beam=SSRL_DCMbeamGlobal01)

    outDict = {
        'UndulatorbeamGlobal01': UndulatorbeamGlobal01,
        'FEMaskbeamLocal01': FEMaskbeamLocal01,
        'C_FilterbeamGlobal01': C_FilterbeamGlobal01,
        'C_FilterbeamLocal101': C_FilterbeamLocal101,
        'CVDFilterAbsorbedPower': CVDFilterAbsorbedPower,
        
        'SSRL_DCMbeamGlobal01': SSRL_DCMbeamGlobal01,
        'SSRL_DCMbeamLocal101': SSRL_DCMbeamLocal101,
        'SSRL_DCMbeamLocal201': SSRL_DCMbeamLocal201,
        
        'SampleScreenFootprint': SampleScreenFootprint}
    return outDict

rrun.run_process = run_process


def define_plots():
    plots = []

    plot01 = xrtplot.XYCPlot(
        beam=r"UndulatorbeamGlobal01",
        xaxis=xrtplot.XYCAxis(
            label=r"x"),
        yaxis=xrtplot.XYCAxis(
            label=r"z"),
        caxis=xrtplot.XYCAxis(
            label=r"energy",
            unit=r"eV"),
        aspect=r"auto",
        title=r"01 - P23 undulator source",
        fluxFormatStr=r"%g")
    plots.append(plot01)
    
    plot02 = xrtplot.XYCPlot(
        beam=r"UndulatorbeamGlobal01",
        xaxis=xrtplot.XYCAxis(
            label=r"x",limits=[-1, 1]),
        yaxis=xrtplot.XYCAxis(
            label=r"z",limits=[-0.2, 0.2]),
       caxis=xrtplot.XYCAxis(
            label=r"energy",
            unit=r"eV"),
       title=r"02 - P23 Undulator total power",
       fluxKind='power')
    plots.append(plot02)
    
    plot03 = xrtplot.XYCPlot(
        beam=r"CVDFilterAbsorbedPower",
        xaxis=xrtplot.XYCAxis(
            label=r"x"),
        yaxis=xrtplot.XYCAxis(
            label=r"y"),
        caxis=xrtplot.XYCAxis(
            label=r"energy",
            unit=r"eV"),
        title=r"03 - CVD Filter Absorbed Power",
        fluxKind=r"power",
        fluxFormatStr=r"%g")
    plots.append(plot03)
         
    plot05 = xrtplot.XYCPlot(
        beam=r"SampleScreenFootprint",
        xaxis=xrtplot.XYCAxis(
            label=r"x"),
        yaxis=xrtplot.XYCAxis(
            label=r"z"),
        caxis=xrtplot.XYCAxis(
            label=r"energy",
            unit=r"eV",
            limits=[4820,4890],
            offset=0),
        title=r"05 - Sample",
        fluxFormatStr=r"%g")
    plots.append(plot05)
    return plots


def main():
    P23_Main = build_beamline()
    E0 = 0.5 * (P23_Main.Undulator.eMin +
                P23_Main.Undulator.eMax)
    P23_Main.alignE=E0
    plots = define_plots()
    xrtrun.run_ray_tracing(
        plots=plots,
        repeats=20,
        backend=r"raycing",
        beamLine=P23_Main)


if __name__ == '__main__':
    main()

```

**Comment by yxrmz** [comment]
Hi, could you explain how large you want the energy range to be and why? DCM will leave a narrow energy band in any case.
If you want to stretch the beam energy peak to tfit the color scale, just narrow down the limits for caxis in plot05.

**Comment by angelicacecilia** [comment]
Good morning.
What I need to calculate is the photon flux at the sample position vs. energy.
I have calculated the photon flux from the source (see figure below):
![figure](https://user-images.githubusercontent.com/46441731/73051931-312f2580-3e84-11ea-9255-656ac381df9e.jpg)
I would need the same figure to detail the photon flux at the sample position (after the monochromator). I wanted to use the script for that.

Thank you in advance for your help.
Best Greetings, Angelica

**Comment by kklmn** [comment]
Hi,

I am not sure auto-alignment works correctly for multilayers. Try to give a real angle.
Visualizing by xrtGlow could be very helpful in checking the optical elements and the beams. Did you try it?

Also, I see that you use a beam with "absorbed intensity" for further propagation. Such beams are meant for plotting of the absorbed power distribution at the optical element where it was absorbed.

When troubleshooting such problems, you don't need a big energy range. Just use one harmonic and the calculations will be _much_ faster. Also, you temporarily don't need auxiliary elements such as slits and filters.

To see where the beam stops, create a plot for each surface ("local" beams in x-y coordinates).

**Comment by angelicacecilia** [comment]
Good afternoon!
I successfully propagated the beam through the DCM and just now I did it also for a Double Multilayer Monochromator (DMM) by using one of the examples that you provide on your website.

I know how to extract the data from the pickle file that corresponds to the picture below.
How can I quantify the flux (ph/s) vs. energy  transmitted from the DMM?

![bm__DMMbeamGlobal01-1](https://user-images.githubusercontent.com/46441731/73199035-63ff4500-4134-11ea-9faa-d35af94755cf.png)

thank you for the help. Angelica

**Comment by kklmn** [comment]
A typical way to extract ray distributions is described [here](https://xrt.readthedocs.io/using.html#saving-the-results), and an example can be found in 
`examples/withRaycing/01_SynchrotronSources/synchrotronSources.py`. In that example, we pickle some values and arrays to be used elsewhere but you can directly do plotting in the function `afterScript`.

For the energy distribution, you need plot.caxis.binEdges and plot.caxis.total1D. The sum under the curve is the number of good rays within the specified energy limits. If you want it in ph/s, normalize it to plot.flux.

It is also possible to extract some values and arrays from plot pickles if you store them. Because pickling requires serialization, a plot pickle is not the same as its corresponding plot itself. The data structure there is different. From a plot pickle you need to extract `ebinEdges`, `etotal1D` and flux is calculated as 
```flux = float(intensity) / nRaysAll * nRaysSeededI / nRaysSeeded```,
where all these variables are present in the pickle.

In the GitHub version, I've now included flux into plot pickles to facilitate its possible future usage.
