### ISSUE TITLE
Surprising dependence as a function of the distance from the source

### ISSUE THREAD

**Issue by vespos** [kklmn/xrt#58]
Hello,

First thank you for putting together this very nice software! We are using it more and more.

We are currently using xrt to simulate some setup we want to test at the LCLS free-electron laser. In this setup, we have a pair of parabolic mirrors as shown below. The idea is to first focus the beam with the first mirror and have a second mirror to restore the initial properties (divergence mainly) of the beam. The overall setup is much more complex, but we identified some issues with this particular subsystem that we need to understand.

In order to simulate the LCLS source, we simply use a GeometricSource with dx=0.02, dy=0.02, dxprime=4E-6 and dzprime=4E-6. To our surprise, we realized that there is a strong dependence on the distance at which this simple setup is placed from the source. As can be seen in the second figure below, the divergence of the beam gets more and more distorted as the setup is moved further away from the source. Note that the distance between the two mirror is kept constant at d=2f. Note that in our simulation, the setup will be at more than 100m from the source, where this effect becomes dramatic and quickly alters the beam shape as it propagates.

We checked using ray transfer matrix analysis of the setup and expect to recover the initial divergence, without any dependence on the source-setup distance.

Is this a normal behavior and there is something we don’t understand in this setup, or is this an artifact of the simulation? We also checked whether there is some beam size dependence by slitting the beam down to its initial size, but the results remain the same.

Thanks in advance for your help,
Vincent Esposito and Hasan Yavas

![image](https://user-images.githubusercontent.com/42768134/74296229-17049c80-4cf8-11ea-9dd6-8ecaacdb52f9.png)
Fig. 1: setup

![fig](https://user-images.githubusercontent.com/42768134/74297019-719ef800-4cfa-11ea-97fe-5169883f295e.png)
[fig.pdf](https://github.com/kklmn/xrt/files/4189523/fig.pdf)
Fig2: Beam 30cm after the setup. Top: (x,z), Bottom: (E,z')

Please find below the code used to generate the above Figure:
```
import numpy as np`
import matplotlib.pyplot as plt

import sys
sys.path.append(r'pathToXrt')

import xrt.backends.raycing as raycing
import xrt.plotter as xrtplot
import xrt.runner as xrtrun

from xrt.plotter import XYCAxis, XYCPlot
from xrt.backends.raycing.sources import GeometricSource
from xrt.backends.raycing.screens import Screen
from xrt.backends.raycing.oes import OE, ParabolicalMirrorParam, EllipticalMirrorParam
from xrt.backends.raycing.materials import Material

def get_perpendicular_vector(v):
    return np.cross([1,0,0], v)

E0 = 4400
m_mat = Material(elements='Au', rho=19.32, kind='mirror')
m_pitch = np.radians(0.2) # mirror pitch
q = 500 # focal distance

D = 5E3 # distance from the source
angle = 2*m_pitch
n = np.array([0,
    np.cos(angle),
    np.sin(angle)]) # unit vector along the beam after first mirror


def build_beamline():
    bl = raycing.BeamLine()

    # Source
    bl.source = GeometricSource(bl=bl, dx=0.02, dy=0.02, dxprime=4E-6, dzprime=4E-6, energies=[E0])
    # bl.source = GeometricSource(bl=bl, dx=0.02, dy=0.02, dxprime=0, dzprime=0, energies=[E0])

    # Optical elements
    bl.oes = []
    ParabolicalMirrorParam(
        bl=bl,
        center=np.array([0,D,0]),
        pitch=m_pitch,
        q=q,
        material=m_mat,
        isCylindrical=True
        )

    ParabolicalMirrorParam(
        bl=bl,
        center=bl.oes[0].center+2*q*n,
        pitch=-m_pitch,
        positionRoll=np.pi,
        q=q,
        material=m_mat,
        isCylindrical=True
        )

    # Screens
    bl.s1 = Screen(
        bl=bl,
        name='source',
        center=np.asarray(bl.source.center)
        )
    bl.s2 = Screen(
        bl=bl,
        name='focus',
        center=bl.oes[0].center+q*n,
        z=get_perpendicular_vector(n)
        )
    bl.s3 = Screen(
        bl=bl,
        name='detector',
        center=bl.oes[1].center+np.array([0,300,0]),
        )

    print('\n\n')
    print('OEs position:')
    print(bl.oes[0].center)
    print(bl.oes[1].center)
    print('\n')
    print('\nScreens position:')
    print(bl.s1.center)
    print(bl.s2.center)
    print(bl.s3.center)
    print('\n\n')
    return bl


def run_process(bl):
    beam = [bl.source.shine()]
    for ii, oe in enumerate(bl.oes):
        beam.append(oe.reflect(beam=beam[ii])[0])
    outDict = {}
    outDict['source'] = bl.s1.expose(beam[0])
    outDict['focus'] = bl.s2.expose(beam=beam[1])
    outDict['detector'] = bl.s3.expose(beam=beam[-1])
    return outDict
raycing.run.run_process = run_process


def define_plots(bl):
    plots = []
    for screen in bl.screens:
        # x-z plot:
        saveName = './plots/dist_'+str(int(D/1000))+'_'+screen.name+'.png'
        plot = XYCPlot(beam=screen.name,
            xaxis=xrtplot.XYCAxis(label="x",fwhmFormatStr='%.3f'),
            yaxis=xrtplot.XYCAxis(label="z",fwhmFormatStr='%.3f'),
            caxis=xrtplot.XYCAxis(label="energy",unit=r"eV",offset=E0,fwhmFormatStr='%.4f'),
            title=screen.name+ '_y' + str(int(screen.center[1])),
            saveName=str(saveName))
        plots.append(plot)
        # E-z' plot:
        saveName = './plots/dist_'+str(int(D/1000))+'_'+screen.name+'._div.png'
        plot = XYCPlot(beam=screen.name,
                xaxis=xrtplot.XYCAxis(label="energy", unit="eV", offset=E0),
                yaxis=xrtplot.XYCAxis(label="z'", unit="urad", factor=1E6),
                caxis=xrtplot.XYCAxis(label="energy",unit="eV",offset=E0,fwhmFormatStr='%.4f',),
                title=screen.name+ '_y' + str(int(screen.center[1])),
                saveName=saveName, aspect='auto')
        plots.append(plot)
    return plots


def main():
    bl = build_beamline()
    bl.alignE = E0
    plots = define_plots(bl)
    xrtrun.run_ray_tracing(beamLine=bl, repeats=1, plots=plots)


if __name__ == '__main__':
    main()
```

**Comment by kklmn** [comment]
Please clarify what you expect to see. What do you see with a strictly parallel source?

Do you understand the meaning of `p` and `q` parameters of ParabolicalMirrorParam? Do you really want `q` for the second one?

**Comment by vespos** [comment]
After the two mirrors, we expect to have the same divergence as the source. If a divergence-less source is used, we see similar effects.

I am indeed a little bit confused with the difference between `p` and `q` in this context. I initially tried with `p` for the second mirror, but then I ended up with 0 good rays at the detector and thus assumed this was not the right way of doing it. Maybe that's the problem.

**Comment by kklmn** [comment]
A parallel source would be more illustrative and quicker to understand...

About p and q. p is the upstream focal distance, q is the downstream focal distance. For a parabolical mirror, either p or q exists, the other one being at infinity. If the parabola axis is not collinear with the beamline, f1 or f2 should be specified instead as a 3D point. Your 2nd mirror clearly needs p, not q.

The intersection of a beam with a surface is determined in xrt by a bracketing method. One bracket assumes the beam fully over the surface while the other bracket assumes it fully under the surface. The initial bracketing interval defaults to ±1m (`raycing.maxHalfSizeOfOE = 1000.`). On such a big scale, the surface may not exist, like in the case of a parabolical mirror: the parabola is limited on one end. In your case, that end is shorter than 1 m. For your parabolic mirrors, you can specify `limPhysY=[-30, 30]` and thus help the bracketing.

**Comment by vespos** [comment]
The bracketing seemed to be the problem and limiting the size of the mirror gives much better results. I can now use the parameter `p` without running into the problem of having only bad rays after the mirror and recover the initial beam divergence as expected.
If I increase the mirror size, at some point the divergence starts acting weird again.

I will check in more details the beam footprint on the mirror, as you suggest.

Thanks a lot for helping out! I think we should be able to wrap up our simulation now!

**Comment by yangfg-bsrf** [comment]
It seems I also encounter a similar problem, but the dependence on the grazing anlge. For the test_param_mirror.py in the test directory, if the xlimit and zlimit is set very small, the difference between grazing angle of 4mrad and 2mrad is observed  and shown in the picture, it seems the position also changes. 
p = 40000.
q = p/1.
pitch = 2e-3

**Comment by kklmn** [comment]
> If I increase the mirror size, at some point the divergence starts acting weird again.

I've tried it now with limPhysY=[-499, 499] and a parallel source and it works, with 0 bad rays. The bracketing breaks at the size ±500. What is your "some point"? Please demonstrate.

**Comment by kklmn** [comment]
> It seems I also encounter a similar problem

No, this is an unrelated story. Here, the screen positioning was not precise enough for your purpose.

Define it like this:
```
dq = (q+dy) * np.cos(2*pitch)  # without the cos() factor in the example
beamLine.fsm2.center[1] = beamLine.ellMirror.center[1] + dq
```
and you will get exact focusing down to fm scale:
![elliptical-roll=0-beamFSM2-3](https://user-images.githubusercontent.com/17322580/74928057-0d0a2a00-53d9-11ea-98ec-4cfdc981b37a.png)

If you want the updated example, you can find it in GitHub.

**Comment by vespos** [comment]
> 
> 
> > If I increase the mirror size, at some point the divergence starts acting weird again.
> 
> I've tried it now with limPhysY=[-499, 499] and a parallel source and it works, with 0 bad rays. The bracketing breaks at the size ±500. What is your "some point"? Please demonstrate.

The bad ray problems kicks in above limPhysY=[-499, 499] as well. 
Things seem to work fine with the divergent source. However, if I use a parallel source `bl.source = GeometricSource(bl=bl, dx=0.02, dy=0.02, dxprime=0,  dzprime=0, energies=[E0])` , I get some strange behavior:

![Capture](https://user-images.githubusercontent.com/42768134/74982440-fbc91980-53e8-11ea-97d5-dbf5f3601584.PNG)

The shape of the divergence on the detector is very much dependent on the `limPhysY` parameter. For the example screenshot here the limits were set to [-499, 499], but for `limPhysY=[-200, 200]` I get:

![Capture](https://user-images.githubusercontent.com/42768134/74983176-64fd5c80-53ea-11ea-960b-0a73be99f6ff.PNG)

Or for `limPhysY=[-20, 20]`:

![Capture](https://user-images.githubusercontent.com/42768134/74984018-0389bd80-53eb-11ea-91b2-98250cd5edeb.PNG)

**Comment by kklmn** [comment]
The transverse coordinates are x and z, so use in your source `dz`, not `dy`.

**Comment by vespos** [comment]
That's right, there was this typo in my code. Luckily the default value for dz is very close (0.018) and correcting for this does not change the intriguing dependence i describe above.

**Comment by kklmn** [comment]
Apparently the number 1e-9 is a matplotlib's scaler for your angular axis in µrad.
To avoid surprises, specify the axis limits yourself.
![image](https://user-images.githubusercontent.com/17322580/74989394-81c47f00-5440-11ea-8401-a7fe11c523bb.png)

**Comment by vespos** [comment]
Fair enough!
Thanks again for the prompt replies. Looks like everything is working as intended now!
