### ISSUE TITLE
degree of coherence

### ISSUE THREAD

**Issue by y19880621** [kklmn/xrt#59]
Hi. I am recently working on calculating degree of coherence. However, I found the unit of the legend never changed even when I set 'unit' in `xrt.backends.raycing.coherence.plot_1D_degree_of_coherence()`. The original codes(start at line 180) exacted from coherence.py show as below. 
`

    legendX = ax3.legend(
        (l1, l3, pp),
        ("I({0}),\nσ$_{0}$ = {1:.2f} mm".format(axisName, varIx**0.5),
         "DoC({0}$_1-${0}$_2$),\nξ$_{0}$ = {1:.2f} mm".format(
             axisName, varJdx**0.5),
         "\nζ$_{0}$ = {1:.1f} %".format(axisName, cohFrx*100)),
        loc=loc)
`

I thought it should be changed to following codes:
`

    legendX = ax3.legend(
        (l1, l3, pp),
        ("I({0}),\nσ$_{0}$ = {1:.2f} {2}".format(axisName, varIx**0.5, unit),
         "DoC({0}$_1-${0}$_2$),\nξ$_{0}$ = {1:.2f} {2}".format(
             axisName, varJdx**0.5, unit),
         "\nζ$_{0}$ = {1:.1f} %".format(axisName, cohFrx*100)),
        loc=loc)
`
And the same problem exists in the example figures on the website.
[https://xrt.readthedocs.io/raycing.html#module-xrt.backends.raycing.coherence](url)

**Comment by kklmn** [comment]
Thank you for reporting it!
I've now corrected the legend labels in the code and the picture on the web page.
