### ISSUE TITLE
Strong Dependency of Total power on mesh density

### ISSUE THREAD

**Issue by marcocamma** [kklmn/xrt#60]
Dear XRT authors,
thanks very much for the effort to put together such power and polished tool
I noticed however that there is a very strong dependence of the total power calculated by `power_vs_K` on the mesh density as demonstrated by the script below.

I tried to find the reason for it but it was too deep down to understand it without a detailed knowledge of the code (I started using xrt only few days ago).
Since memory and computing time scales with the number of points in the mesh I was wondering if there is any way to have a more "energy preserving" way of estimating the power.

SRW is much less sensitive to these parameters as shown by the little "video" below
https://asciinema.org/a/316263
It uses a little (untested) layer I wrote (https://github.com/marcocamma/sr) but it essentially uses SRW   function `CalcStokesUR` behind the scene.

Is there something I am not getting right in the way XRT should be used ?
Thanks in advance for your comments !
Marco Cammarata (scientist at ESRF as you could guess from the electron beam parameters ... )

ps. SRW has also another way of calculating power densities and total power (`CalcPowDenSR`) that is even faster and less sensitive to the mesh density (https://asciinema.org/a/316259)

```import numpy as np
import xrt.backends.raycing.sources as rs


kwargs = dict(
    eE=6,
    eI=0.2,
    eSigmaX=30.0,
    eSigmaZ=3.6,
    eEpsilonX=0.132,
    eEpsilonZ=0.005,
    eEspread=0.00089,
    period=18,
    n=111,
    K=1.76,
    xPrimeMax=2e-3/30, # 10mm at 30 m
    zPrimeMax=2e-3/30, # 10mm at 30 m
    distE="BW",
)

undulator = rs.Undulator(**kwargs)

print("This script will demonstrate the dependence of the calculated power trough a 2x2 mm slit at 30 m as function of the number of points in the mesh")

energies = np.linspace(5e3,20e3,1501)
harmonics = (1,)
Ks = (undulator.K,)

for npoints in (2,3,10):
    theta = np.linspace(-1,1,npoints)*1e-3/30
    psi   = np.linspace(-1,1,npoints)*1e-3/30
    power = undulator.power_vs_K(energies,theta,psi,harmonics,Ks)
    power = float(power)
    print(f"npoints = {npoints:2d}x{npoints:2d}, {power:7.2f} W")
```

**Comment by kklmn** [comment]
Hi!

Yes, total power does depend on mesh density. Please look at the xrt's front web page, the very first animation. Do you really expect that such a transverse profile can be sampled on a 2×2 mesh? It must depend on the mesh but it must converge with the mesh getting finer.

Keep in mind that internally method `power_vs_K` also samples over the energy spread, so the final mesh becomes _multi_ dimensional and quickly grows huge. Therefore for power calculations you should set `eEspread` to 0. It doesn't really change the power. After setting it 0, I get the convergence (where whether you include the origin in XZ or not can matter, especially at small npoints):

```
npoints =  2x 2,  519.34 W
npoints =  5x 5,  277.98 W
npoints = 10x10,  231.27 W
npoints = 20x20,  212.16 W
npoints = 50x50,  201.80 W
npoints = 100x100,  198.52 W
npoints = 200x200,  196.91 W

npoints =  3x 3,  364.53 W
npoints =  6x 6,  260.98 W
npoints = 11x11,  227.61 W
npoints = 21x21,  211.31 W
npoints = 51x51,  201.67 W
npoints = 101x101,  198.49 W
npoints = 201x201,  196.90 W
```

Note 1:
Energy mesh matters as well. If you don't sample a harmonic well enough, you may lose its power.

Note 2:
`xPrimeMax` and `zPrimeMax` and given mrad, as writen in [rtfd](https://xrt.readthedocs.io/raycing.html#xrt.backends.raycing.sources.Undulator).

Note 3:
I did power calculations for all MAX IV beamlines for our Rad Safety group. What I have found, to very good accuracy, you don't need the Undulator class. Use Wiggler (it doesn't have `harmonics` key word) in the same way, it is much faster.

**Comment by marcocamma** [comment]
Thanks a lot for the answer !
Of course I understand the spatial dependency but it depends how values are calculated you can be more or less sensitive to it.

If the density is obtained by dividing the integral over the solid angle by the solid angle then it is virtually not sensitive at all on the number of points. I have the feeling that this is the way SRW works as spectral distributions and total power have little (if any) dependence on the mesh density.

Maybe adding a note to the doc string of `power_vs_K` could be good, at least as users we are warned. Do you want me to propose a sentence or two as pull request ?

As for your tips (eEspread set to zero and Wiggler class): thanks a lot ! I will try them as soon as I can.

**Comment by kklmn** [comment]
> If the density is obtained by dividing the integral over the solid angle by the solid angle ...

No, we don't do this. Our power density is just intensity (factored by 1/0.1%) when calculated per bw or intensity times energy when calculated per eV. Intensity is a local characteristic for a given observation direction and given energy, see [here](https://xrt.readthedocs.io/raycing.html#synchrotron-sources) for how we calculate it.

We do optimize the mesh along the electron trajectory but we don't use any mesh for the observation direction or energy, this method `power_vs_K` is one of a few exceptions. We normally don't need meshes because we do MC sampling, both in ray tracing and in wave propagation. Gridding is one reason why SRW is orders of magnitude slower, see duration figures [here](https://xrt.readthedocs.io/raycing.html#single-electron-and-multi-electron-undulator-radiation). The first example in [Gallery 2](https://xrt.readthedocs.io/gallery2.html) shows a calculation of power and isolines of power density by ray tracing, i.e. without a need for gridding, maybe this is what you want.

I've added a reminder in the docstrings of `power_vs_K` that numerical integration is mesh dependent.

**Comment by marcocamma** [comment]
reminder in docstring will help future users.
Thanks a lot !
