### ISSUE TITLE
Aperiodic Multilayers

### ISSUE THREAD

**Issue by NolannR** [kklmn/xrt#62]
Hello,

I would like to simulate an aperiodic multilayer coating on XRT. As far as I know, we can only do a periodic multilayer and a depth-graded multilayer. I would like to perform a fine simulation that includes the interface effects, so ideally we would be able to add a 3rd material. For example, in case of Mo/Si, we can add MoSi2.

At the end, ideally an user could simulate an arbitrary coating (aperiodic) with an arbitrary number of materials (2 or more).

Thank you in advances for your answers.

**Comment by kklmn** [comment]
Hi,

For aperiodic layers:
Inherit from `materials.Multilayer` and modify `get_t_thickness(self, x, y, iPair)` and `get_t_thickness(self, x, y, iPair)`, see their description [here](https://xrt.readthedocs.io/raycing.html#xrt.backends.raycing.materials.Multilayer.get_t_thickness).

For an arbitrary number of layer materials, you'd need to modify `get_amplitude()`. Where it has `if i % 2 == 0:`, you should have `if i % {your_number_of_materials} == 0:` and provide the thickness of that material.
If you have experimental examples that you agree to share, I could make a multi-material multilayer.
