### ISSUE TITLE
method for wave propagation 

### ISSUE THREAD

**Issue by yangfg-bsrf** [kklmn/xrt#71]
Hi, after check the code in XRT backend, I  found it is some different from the SRW, which uses the fresenl diffraction integration. XRT uses the Monte Carlo sampling and integration instead in diffraction,  would you please tell me how to understand it? is it OK if we use uniform sampling method?

**Comment by kklmn** [comment]
Hi,

>would you please tell me how to understand it? 

Please read the section [Wave propagation (diffraction)](https://xrt.readthedocs.io/raycing.html#wave-propagation-diffraction). I think the whole section answers your question. Please ask about any particular aspect. You may also include an example.

>is it OK if we use uniform sampling method?

The sampling in our wave propagation is de facto uniform. You can create the samples yourself but the usual way is to utilize `prepare_wave` (which creates uniform samples except for a screen where the sampling is on its pixel grid) before `diffract`, as explained in the subsection [Usage](https://xrt.readthedocs.io/raycing.html#usage).

Before you deeply compare with SRW, please consider [Tests of Kirchhoff integral with various Gaussian beams](https://xrt.readthedocs.io/test_waves.html#tests-of-kirchhoff-integral-with-various-gaussian-beams). The tests compare our implementation of numerical Kirchhoff diffraction with various analytical Gaussian beams. What is quite important in the tests, is that the total flux is preserved upon empty space propagation. The tests are also important to see that the results converge (saturate) upon increasing the number of the field samples. Please go through the tests and a few examples to understand the machinery of our implementation.

**Comment by kklmn** [comment]
To add, the tests with Gaussian beams use mesh sampling for both the source and the receiving surface (the screen). For wave propagation through optical elements, we typically use uniform random sampling but this is not a must, meshes may also work fine. The main advantage of random samples vs mesh samples is that we do not interfere with any possible periodicity: in gratings, FZPs, or patterned figure errors.

**Comment by yangfg-bsrf** [comment]
en, for the first question, taking the `_diffraction_integral_conv` for example,  the ray direction is determined by the following code?  In my opinion, the direction of the ray is determined by the wavefront. Here it is calculated by  weight, they are equal?
```
def _diffraction_integral_conv(oeLocal, n, nl, wave, good):
    ...
    abcU = k**2/(4*np.pi) * (oeLocal.Es[good]+oeLocal.Ep[good]) * U / pathAfter
    aE = (abcU * a).sum(axis=1)
    bE = (abcU * b).sum(axis=1)
    cE = (abcU * c).sum(axis=1)
   ...
    return Es, Ep, aE, bE, cE
```

**Comment by kklmn** [comment]
First, note that this method is for "conventional" calculations, i.e. without OpenCL, which in practice is never possible and the method is never used. The one used is `_diffraction_integral_CL`. Both of them are not interfaced directly by the user.

Yes, these are wavefront normals calculated as described [here](https://xrt.readthedocs.io/raycing.html#sequential-propagation). The verification of this approach is also described under the formula. Note that the wave gradient (that defines the wavefront normals) is calculated not separately for the two polarizations but for their sum. I tested this aspect extensively and found out that for both polarizations the gradient integral is practically the same. This happens so because the phase factor is by far much more important than the amplitude factor under the integral. So I just symmetrize the integral and take the sum of the two field amplitudes.

**Comment by yangfg-bsrf** [comment]
> First, note that this method is for "conventional" calculations, i.e. without OpenCL, which in practice is never possible and the method is never used. The one used is `_diffraction_integral_CL`. Both of them are not interfaced directly by the user.

> Yes, these are wavefront normals calculated as described [here](https://xrt.readthedocs.io/raycing.html#sequential-propagation). The verification of this approach is also described under the formula. Note that the wave gradient (that defines the wavefront normals) is calculated not separately for the two polarizations but for their sum. I tested this aspect extensively and found out that for both polarizations the gradient integral is practically the same. This happens so because the phase factor is by far much more important than the amplitude factor under the integral. So I just symmetrize the integral and take the sum of the two field amplitudes.

Thanks for your remind, I got what you mean for the aE, bE, cE calculation. The equation is so similar to the U, I did not notice it . Yea, so far, the comparison between the XRT and SRW made me believe its validation.

**Comment by yangfg-bsrf** [comment]
for the second question, what I mean for the uniform sampling is the grid sampling, same with that by screen prepare_wave.  I think you have given me the answer. I am trying to understand the implementation and figure out what happened. 

> > is it OK if we use uniform sampling method?
> 
> The sampling in our wave propagation is de facto uniform. You can create the samples yourself but the usual way is to utilize `prepare_wave` (which creates uniform samples except for a screen where the sampling is on its pixel grid) before `diffract`, as explained in the subsection [Usage](https://xrt.readthedocs.io/raycing.html#usage).
> 
> Before you deeply compare with SRW, please consider [Tests of Kirchhoff integral with various Gaussian beams](https://xrt.readthedocs.io/test_waves.html#tests-of-kirchhoff-integral-with-various-gaussian-beams). The tests compare our implementation of numerical Kirchhoff diffraction with various analytical Gaussian beams. What is quite important in the tests, is that the total flux is preserved upon empty space propagation. The tests are also important to see that the results converge (saturate) upon increasing the number of the field samples. Please go through the tests and a few examples to understand the machinery of our implementation.
