### ISSUE TITLE
Difference between the geometrical tracing and wave propagation

### ISSUE THREAD

**Issue by yangfg-bsrf** [kklmn/xrt#74]
Hi, I have one question about the difference between the geometric tracing and wave propagation. As shown in the simulation of  SoftiMAX beamline, 
https://xrt.readthedocs.io/gallery3.html#stxm-branch
![image](https://user-images.githubusercontent.com/41823786/113145306-dc91f200-9260-11eb-9905-8201cdc79453.png)
the focusing spot size of rays tracing is bigger than that of wave case.  I wonder what the reason is for this issue?
In my recent simulation case, the difference seems larger as shown below, where emittance and energy spread are all zero.
![image](https://user-images.githubusercontent.com/41823786/113145502-1105ae00-9261-11eb-93b1-28229cf2a3dc.png)
would you please give some suggestion on how to check the validation of the simulation results?

**Comment by yangfg-bsrf** [comment]
In addition, even for the non-zero emittance case, the wave propagation results does not change much. 
In this simulation, the source is almost completely coherent.

**Comment by kklmn** [comment]
Hi,

The discrepancy can be for two reasons: 1) wrong source size and 2) wrong beam propagation.

Let's check the former. The real source size depends on many things, first of all on where is your energy relative to the undulator peak. The source distributions that you show above were somehow _artificially_ constructed as described [here](https://xrt.readthedocs.io/raycing.html#undulator-source-size). If you do wave propagation, you can directly find the real source distribution like this: put a 1:1 ellipsoidal mirror at far enough distance, check with a geometrical source that you get zero-sized focus with rays, and then see the undulator source distribution visualized by this mirror in waves. Now, when you scan your energy over the harmonic peak, you will see how your energy distribution changes. My guess is that your energy is set a bit lower than the formal harmonic energy.

There is yet another way to calculate the linear source distribution: propagate the phase back to the source and do a 2D FT, as first done by Coïsson and later used by Tanaka&Kitamura. I have all the calculations and pictures for a paper dealing with the topic of source size influenced by many factors and compared with the Wigner function approach. The paper is stalled now. So far, I have [this small chapter](https://xrt.readthedocs.io/raycing.html#undulator-source-size-dependent-on-energy-spread-and-detuning), where the inset in the left plot supports my guess about your energy detuning towards lower energy. The lines there are the artificial linear sizes. You can also see there that the source visualization by a 1:1 ideal mirror in waves (open circles) and the Coïsson method (crosses) give very close results.

You are welcome to post here your curve of the source size as a function of energy detuning.

**Comment by yangfg-bsrf** [comment]
thanks for your suggestion. you are right. the energy difference cause the difference. 
![image](https://user-images.githubusercontent.com/41823786/113230327-6080c400-92cb-11eb-89a5-45e7b10f69ca.png)

![Depth_Of_Focus](https://user-images.githubusercontent.com/41823786/113230371-72fafd80-92cb-11eb-8e73-01a8b50d5eed.png)

**Comment by kklmn** [comment]
Great! Thanks for sharing.
