### ISSUE TITLE
Depth distribution mosaic crystal

### ISSUE THREAD

**Issue by bbazi** [kklmn/xrt#77]
![depth distriburion mosaic crystal](https://user-images.githubusercontent.com/82967994/115597386-82250800-a2d9-11eb-838d-4da6ef98287e.png)
Hi, could you comment on how a penetration depth distribution is calculated for a mosaic crystal. 
I would like to make such depth calculations for graphite crystals using various mosaicity values and incident energies.
See picture for the example on the XRT website.

**Comment by kklmn** [comment]
Hi, 
As you may guess from the noise, it needs MC sampling, there is no analytic function for it in xrt.
The script `tests/raycing/test_mosaic_xtal.py` makes the plot. If you can't dig it, please get back with questions.

**Comment by bbazi** [comment]
![FileNotFoundError](https://user-images.githubusercontent.com/82967994/115614226-b99daf80-a2ed-11eb-8024-b459e3ed9881.png)
Thanks for the quick reply!
I am trying to reproduce the depth distribution plot but I got the following error (see picture).
Am I missing a certain file or directory?

**Comment by kklmn** [comment]
yes, this pickle file first has to be produced and only then analyzed/plotted. 
At the very end of the script first select `main()` and then `plot_reflectivity()`

**Comment by bbazi** [comment]
![Depth distribution graphite (002) mosaic FWHM 0 1deg](https://user-images.githubusercontent.com/82967994/115699050-94e51e80-a365-11eb-8fb2-a9cc5bb120d0.png)
Hi, I could reproduce the example and I also made one with the following parameters:
(002) reflection, mosaicity FWHM 0.1°, E = 4.647 keV & 8.146 keV
It would be much appreciated to see if you can reproduce this plot.

**Comment by kklmn** [comment]
Anonymous appreciation is not a strong motivation. I will do it if you provide verification by another method.
