### ISSUE TITLE
Cylinder optics with strong curvature

### ISSUE THREAD

**Issue by bbazi** [kklmn/xrt#79]
![Nd-La1 on SLcam(png)](https://user-images.githubusercontent.com/82967994/119635407-f04a7680-be13-11eb-893b-8e47ddc37e14.png)
![vH_optic_code](https://user-images.githubusercontent.com/82967994/119635409-f17ba380-be13-11eb-8454-1c7bb58172ba.png)
![vH_optic_polygons](https://user-images.githubusercontent.com/82967994/119635410-f17ba380-be13-11eb-95ee-baaa65de8f4b.png)
![vH_rays_diffracted_by_optic](https://user-images.githubusercontent.com/82967994/119635414-f2acd080-be13-11eb-91e9-b2525335031b.png)
Hi,
I tried to simulate a vonHamos spectrometer which has a cylinder optic with strong spatial curvature using the "JohannToroid" OE (see picture).
Rs=3.901mm, should be 3.9mm to be exact but this gives ray tracing errors on the optic's surface.
Unfortunately, the optic's surface is not smooth-like but has these polygons (see picture).
This has the result of not giving Bragg diffraction on the entire optic's surface which is also visible on the detector screen (see pictures).

What would you recommend to have a better representation of the cylinder optic so that the entire surface can be used for Bragg diffraction? Is there maybe an example that could help me?

Thanks for your time, cheers,
Benjamin Bazi

**Comment by kklmn** [comment]
Hi,
The smoothness of surfaces is controlled by two tessellation parameters in the 'Scene' tab. You can make it smoother with larger values at the cost of calculation load. But this is only a visual representation, it is not related to the actual ray tracing. I think that what you get is the real physical result: yes, a von Hamos optic is rather inefficient.

**Comment by bbazi** [comment]
Hi,

Thanks for the comment!
Which OE would you suggest to change this half-cylinder to a full-cylinder?
Is it then also mandatory to use the parametric equations?  

Cheers,
Benjamin

**Comment by kklmn** [comment]
Some closed surfaces can be described by a function of x and y coordinates, e.g. a cone in some orientations, but a straight cylinder definitely cannot. So it has to be in a parametric representation. I have some parametric examples in `02_vonHamosElliptical.py`. 

A simple full cylinder can look like this:
```
class Cylinder(roe.SurfaceOfRevolution):
    def __init__(self, *args, **kwargs):
        self.r = kwargs.pop('r')
        super(Cylinder, self).__init__(*args, **kwargs)

    def local_r(self, s, phi):
        return self.r

    def local_n(self, s, phi):
        a = -np.sin(phi)
        b = np.zeros_like(s)
        c = -np.cos(phi)
        return a, b, c
```

I am not sure how extensively closed surfaces were tested with xrtGlow. Please let us know in case of trouble.

**Comment by bbazi** [comment]
Here's the cylinder code I used with xyz_to_param and param_to_xyz:

`Rs = 3.9
class CylindervH(roe.SurfaceOfRevolution):
    def __init__(self, *args, **kwargs):
        self.Rs = kwargs.pop('Rs')
        super(CylindervH, self).__init__(*args, **kwargs)

    def local_r(self, s, phi):
        return self.Rs

    def local_n(self, s, phi):
        a = -np.sin(phi)
        b = np.zeros_like(s)
        c = -np.cos(phi)
        return a, b, c

    def xyz_to_param(self, x, y, z):
        s = y
        phi = np.arctan(x / (Rs-z))
        r = np.sqrt(x**2 + (Rs-z)**2)
        return s, phi, r

    def param_to_xyz(self, s, phi, r):
        x = r * np.sin(phi)
        y = s 
        z = Rs - r * np.cos(phi)
        return x, y, z
`
Unfortunately, xrtGlow doesn't show a closed surface (see picture).
Maybe you see a mistake in the used parametric equations?
![Cylinder_parametric](https://user-images.githubusercontent.com/82967994/119713553-1bf44d80-be62-11eb-9643-392be7cdd878.png)

**Comment by kklmn** [comment]
Hi, I've enabled closed surfaces in xrtGlow, please download the current version from GH.
<img src="https://user-images.githubusercontent.com/17322580/120102121-d37ead80-c149-11eb-857b-32bcb43d2adb.png" width="360">
Here is the script I used to create the 'beamline' and visualize it in xrtGlow:
[closedCylinder.zip](https://github.com/kklmn/xrt/files/6566109/closedCylinder.zip)
First run it as is and then set `showIn3D = True` and see it is xrtGlow. Enable the surface in Navigation and increase OE tessellation parameters in Scene.

**Comment by bbazi** [comment]
Hi, 
Thanks for the updated version!
During testing I saw that adding a material (in this case a mosaic crystal) to the "SurfaceOfRevolution" OE, the cylinder in xrtGlow gets some unwanted shapes, see picture.
![Cylinder_with_material](https://user-images.githubusercontent.com/82967994/120462933-afb2a600-c39b-11eb-8ed5-789eab6b804d.png)
Here is also the script I used for the vonHamos spectrometer:
[vH_Spectrometer.zip](https://github.com/kklmn/xrt/files/6583674/vH_Spectrometer.zip)

**Comment by kklmn** [comment]
These shapes were the other 5 faces that we draw for the optic body. I've removed them now for closed surfaces. Please again get it from GH.

**Comment by bbazi** [comment]
Hi, thanks again for the update.
Everything looks good!
