### ISSUE TITLE
The xrtGlow does not launch in my xrtQook

### ISSUE THREAD

**Issue by zzw840** [kklmn/xrt#80]
When I tried to use Ctrl+F1 to launch xrtGlow, nothing popped up. What's more, I do not see the xrtGlow-relevant icons (like the blue-red glasses one) in my xrtQook. Can you help please?

**Comment by zzw840** [comment]
Not even the GPU icon.

P.S. I installed xrt using `pip install xrt` in my Anaconda3.

**Comment by yxrmz** [comment]
Hi, it looks like pyopengl is missing. Try
`pip install pyopengl pyopengl_accelerate`

**Comment by zzw840** [comment]
I installed the two libs. Now it looks like my `OpenGL` has a problem..

This is what I got when I tried to launch `xrtGlow` by clicking the blue-red glasses icon.
```
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\xrt\gui\xrtGlow\__init__.py", line 4242, in initializeGL
    gl.glutInit()
  File "D:\Anaconda3\lib\site-packages\OpenGL\GLUT\special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "D:\Anaconda3\lib\site-packages\OpenGL\platform\baseplatform.py", line 423, in __call__
    raise error.NullFunctionError(
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
```

**Comment by kklmn** [comment]
Please follow [TFM](https://xrt.readthedocs.io/instructions.html#instructions) to get it correctly installed.

**Comment by zzw840** [comment]
Hi @yxrmz, thanks for the instruction. However, it still gave me the same error even after I downloaded and pipped those wheels for my platform and python version.

**Comment by yxrmz** [comment]
I hope you uninstalled the first instance of pyopengl before installing the wheel?
Just as a test - try a new clean anaconda env. It's a well known error with glut, and the solution is 100% about the correct installation of pyopengl - try to google for "undefined function glutInit"

**Comment by zzw840** [comment]
All set! I remove the old `PythonGL` and reinstalled again then it worked!
