### ISSUE TITLE
NotImplementedError with Spyder IDE

### ISSUE THREAD

**Issue by Cathyhjj** [kklmn/xrt#81]
Dear developer,

Thanks a lot for the very cool package! 
One problem I am facing is, when I run the code in Spyder IDE, it raises NotImplementedError.
Following is the error I copied from the Spyder when I was running the example code (Jupyter notebook also doesn't work) "**\examples\withRaycing\03_LaueMono\01_bentLaueSCM.py**":

Instead, when I am running the code NOT with the built-in console in Spyder, the code works. 
May I ask what may be the reason for this? 
Thank you very much in advance!
Best regards,
Juanjuan

---------------------------------------------------------------------------------------------------

> Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 7.22.0 -- An enhanced Interactive Python.
> 
> runcell(0, 'C:/Users/Philip/Downloads/xrt-1.3.5/xrt-1.3.5/examples/withRaycing/03_LaueMono/01_bentLaueSCM.py')
> The last 10 runs
> C:/Users/Philip/Desktop/temp.py::
> start: Wed, 26 May 2021 23:06:44; stop: 23:06:46; duration: 1.8 s
> C:/Users/Philip/Desktop/temp.py::
> start: Wed, 26 May 2021 23:08:03; stop: 23:08:06; duration: 2.5 s
> C:/Users/Philip/Desktop/temp.py::
> start: Wed, 26 May 2021 23:09:13; stop: 23:09:15; duration: 2.0 s
> C:/Users/Philip/Desktop/temp.py::
> start: Wed, 26 May 2021 23:10:00; stop: 23:10:02; duration: 2.0 s
> C:/Users/Philip/Desktop/temp.py::
> start: Wed, 26 May 2021 23:10:56; stop: 23:10:59; duration: 2.5 s
> C:/Users/Philip/Desktop/temp.py::
> start: Wed, 26 May 2021 23:11:05; stop: 23:11:07; duration: 2.0 s
> C:/Users/Philip/Desktop/temp.py::
> start: Wed, 26 May 2021 23:36:13; stop: 23:36:16; duration: 2.3 s
> C:/Users/Philip/Desktop/temp.py::
> start: Wed, 26 May 2021 23:39:42; stop: 23:39:44; duration: 2.1 s
> C:/Users/Philip/Desktop/temp.py::
> start: Wed, 26 May 2021 23:40:14; stop: 23:40:16; duration: 2.2 s
> C:/Users/Philip/Desktop/temp.py::
> start: Wed, 26 May 2021 23:41:44; stop: 23:41:46; duration: 2.2 s
> 
> Process BackendProcess-1:
> Traceback (most recent call last):
>   File "C:\Users\Philip\anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
>     self.run()
>   File "C:\Users\Philip\anaconda3\lib\site-packages\xrt\multipro.py", line 265, in run
>     raycing_output = raycing.run.run_process(self.card.beamLine)
>   File "C:\Users\Philip\anaconda3\lib\site-packages\xrt\backends\raycing\run.py", line 6, in run_process
>     raise NotImplementedError  # abstract
> NotImplementedError
> Process BackendProcess-2:
> Traceback (most recent call last):
>   File "C:\Users\Philip\anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
>     self.run()
>   File "C:\Users\Philip\anaconda3\lib\site-packages\xrt\multipro.py", line 265, in run
>     raycing_output = raycing.run.run_process(self.card.beamLine)
>   File "C:\Users\Philip\anaconda3\lib\site-packages\xrt\backends\raycing\run.py", line 6, in run_process
>     raise NotImplementedError  # abstract
> NotImplementedError
> Process BackendProcess-3:
> Traceback (most recent call last):
>   File "C:\Users\Philip\anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
>     self.run()
>   File "C:\Users\Philip\anaconda3\lib\site-packages\xrt\multipro.py", line 265, in run
>     raycing_output = raycing.run.run_process(self.card.beamLine)
>   File "C:\Users\Philip\anaconda3\lib\site-packages\xrt\backends\raycing\run.py", line 6, in run_process
>     raise NotImplementedError  # abstract
> NotImplementedError
> Process BackendProcess-4:
> Traceback (most recent call last):
>   File "C:\Users\Philip\anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
>     self.run()
>   File "C:\Users\Philip\anaconda3\lib\site-packages\xrt\multipro.py", line 265, in run
>     raycing_output = raycing.run.run_process(self.card.beamLine)
>   File "C:\Users\Philip\anaconda3\lib\site-packages\xrt\backends\raycing\run.py", line 6, in run_process
>     raise NotImplementedError  # abstract
> NotImplementedError
> 
> 
>

**Comment by kklmn** [comment]
Hi,

The Jupyter architecture does not support multiprocessing, e.g. see [here](https://stackoverflow.com/questions/23641475/multiprocessing-working-in-python-but-not-in-ipython).

With some ugly workarounds, it is possible to make it work in IPython in Windows but I don't see any point in it.
I simply don't use IPython because I see restrictions and slowness and not any help for my usual workflow.

If you anyway like Spyder's IPython console, either go to Linux or switch off multiprocessing.

**Comment by Cathyhjj** [comment]
Thank you so much for your replies and detailed explanation! 
I think I'll stop using ipython for the package :)

**Comment by yxrmz** [comment]
I usually downgrade my winpython spyder to version 3.1.4 - the last one with embedded python console, works well with all python versions. Anaconda is a bit pickier in this sense, and doesn't offer such downgrade anymore, but nevertheless, pip downgrade works there too.

**Comment by Cathyhjj** [comment]
This is a good idea! Thank you so much!

> I usually downgrade my winpython spyder to version 3.1.4 - the last one with embedded python console, works well with all python versions. Anaconda is a bit pickier in this sense, and doesn't offer such downgrade anymore, but nevertheless, pip downgrade works there too.
