### ISSUE TITLE
Bent asymmetric Laue crystal simulations

### ISSUE THREAD

**Issue by Cathyhjj** [kklmn/xrt#84]
Dear developer,

I was trying to simulate the diffracted beam from a divergent & polychromatic source in combination with a bent asymmetric Laue crystal. As the crystal has an asymmetry angle (64.76 deg,1.13 rad), I would expect to see two different conditions, which were also confirmed by my experiment (here I denote them as "upper" and "lower" condition, see the following illustrations and screenshots from Glow. 
![image](https://user-images.githubusercontent.com/21668972/122924933-98e1ec80-d366-11eb-8435-cd3422349971.png)
The first condition, the "auto" pitch value returned by xrt is the same as what I calculated (just with additional minus sign): ![img](https://latex.codecogs.com/svg.latex?&space;-(\pi/2-(\alpha+\theta_{Bragg}))) . 
And the diffracted beam is observed at a distance of around **128 mm**
![20210622_upper_CCD_at_40cm](https://user-images.githubusercontent.com/21668972/122925128-d21a5c80-d366-11eb-9997-08431e24fe1d.png)

The second condition, I use pitch value![img](https://latex.codecogs.com/svg.latex?&space;-(\pi/2-(\alpha-\theta_{Bragg}))). And there is diffracted beam at this angle.  In principle, the Laue diffracted beam should be observed at the same distance as the first condition because the Bragg angle never gets changed. However, the simulation returns me a different distance at about **83 mm**, which can be also seen in the Glow images. 

![20210622_lower_CCD_at_40cm](https://user-images.githubusercontent.com/21668972/122923966-86b37e80-d365-11eb-9f09-3ba801b337aa.png)

I have been trying to tune the geometries for a long time, could not find out the reason. I also attached the XML file of the second condition (the only difference with the first condition is the pitch value of BentLaueCylindrical crystal.)

[20210621_bent_Laue_Si_311_second_condition.zip](https://github.com/kklmn/xrt/files/6694270/20210621_bent_Laue_Si_311_second_condition.zip)
Could you kindly indicate what might be the reason?

Thanks a lot in advance!
Best regards,
Juanjuan

**Comment by kklmn** [comment]
Hi!
As I understand, you want to compare a few cases. Your zip provides only one.
If you want me to follow your cases, better provide a script where cases can be easily switched.
What is the refractive correction angle at your conditions?

**Comment by Cathyhjj** [comment]
Thanks for the reply! 

I have now attached the python script where I added an option at the beginning which can quickly switch two conditions:
`# Flag`
`condition = "condition_1"`
`condition = "condition_2" `
[20210623_bent_Laue_two_conditions.zip](https://github.com/kklmn/xrt/files/6700715/20210623_bent_Laue_two_conditions.zip)

The Laue diffracted beam should be observed at **distance_to_crystal * np.tan(2*Bragg_angle)**. For the energy, I used 24.5 keV and Si(311), so the first condition's screen's _x_ value ~128 mm is correct. But I don't know why the second one appears at ~83 mm. 

I am not sure what exactly is "refractive correction angle"? Do you mean these functions? 
`In[86]: crystalSi.get_refractive_correction(24500,alpha =1.1302856637901981)`
`Out[86]: -7.66373910896311e-07`
`In[87]: crystalSi.get_dtheta(24500,alpha =1.1302856637901981)`
`Out[87]: -3.685620421990584e-07`

**Comment by kklmn** [comment]
I see in the 1st case your sketch and the Glow rays look similarly, whereas in the 2nd case on your sketch the beam bends up but in Glow it goes down. Maybe you want alpha of the other sign there?

**Comment by Cathyhjj** [comment]
Thanks for the suggestion! 
I tried again yesterday with your suggestion of changing alpha to minus and flipped the geometry to the following:
![image](https://user-images.githubusercontent.com/21668972/123243684-8b9e3c80-d4e3-11eb-8552-174dffc1d357.png)

It works now! Thanks so much!
![image](https://user-images.githubusercontent.com/21668972/123243884-b5effa00-d4e3-11eb-9c97-cda83523c30c.png)
