### ISSUE TITLE
extraPitch for EllipticalMirrorParam

### ISSUE THREAD

**Issue by wholingfei** [kklmn/xrt#86]
Hi, I did some elliptical mirror misalignment analysis using EllipticalMirrorParam class recently. 

I presume the "extraPitch" is designed for easier misalignment implementation. However, I found the EllipticalMirrorParam.ellipseB will change when I applied the "extraPitch". As a result, I have to avoid using "extraPitch" for misalignment checking. 

I'm sorry to ask is there any misunderstanding from me?

**Comment by kklmn** [comment]
Hi,

Indeed, in this class pitch angle is used to define the mirror's ellipse axes. Also `extraPitch` is part of these calculations. You are right, the extra angles should not modify the shape; this is not their meaning.

Please go to oes.py, line ~1172 :meth:`_to_global(self, lb)`, and comment out the first 5 lines that use extra angles. The extra angles will still be used in the mirror positioning but now not in the shape definition. Please tell if the results are correct.

Thanks!

**Comment by wholingfei** [comment]
Hi,
After commenting out the first 5 lines of  `_to_global(self, lb)`, the results look correct.

Thanks very much for your reply!

**Comment by kklmn** [comment]
Ok, thanks!
I've updated the GH version of it.
