### ISSUE TITLE
OE for elliptical KB mirrors

### ISSUE THREAD

**Issue by bbazi** [kklmn/xrt#87]
Hi,
Which OE do you recommend for implementing elliptically curved KB mirrors?
So far I tried working with EllipticalMirrorParam, here is the code for the vertical (KBV) and horizontal (KBH) focusing mirrors:
`

        beamLine.kbv = roe.EllipticalMirrorParam(
            beamLine, 'KBV', [0, 61000., height],
            surface=('Rh',), material=(stripeRh,),
            limPhysX=(-13., 13.), limPhysY=(-70., 70.),
            pitch=3.1e-3, f1=[0, 59000., 57.801], q=310.,
            alarmLevel=0.)

        beamLine.kbh = roe.EllipticalMirrorParam(
            beamLine, 'KBH', [0, 61110., height],
            surface=('Rh',), material=(stripeRh,),
            limPhysX=(-13., 13.), limPhysY=(-35., 35.),
            positionRoll=math.pi/2, 
            extraPitch=3.1e-3,
            f1=[0, 59000., 57.801], q=200.,
            alarmLevel=0.)` 

Both mirrors have a 3.1 mrad Rh coating, extraPitch was used instead of pitch for the KBH because of the interaction with positionRoll.
I'm using the latest GH version. 
The KBV has an unwanted spatial curvature and the KBH stretches out into infinity. It is also not clear if both mirrors display the right elliptical meridional curvature due to its large value.
![KB xrtGlow](https://user-images.githubusercontent.com/82967994/125168988-79d9bc00-e1a8-11eb-8f8a-506308909165.png)

**Comment by kklmn** [comment]
Hi,

Yes, I would use `EllipticalMirrorParam`.

>The KBV has an unwanted spatial curvature 

You probably mean the sagittal curvature. From TFM:
```
    If *isCylindrical* is True, the figure is an elliptical cylinder, otherwise
    it is an ellipsoid of revolution around the major axis.
```

>and the KBH stretches out into infinity. 

This is probably different view scalings along Y and (X, Z). The former is much compressed by default. You can make them equal.

>extraPitch was used instead of pitch for the KBH because of the interaction with positionRoll.

There is no such interaction, just the sequence should be right. For M2, I would first do positionRoll, then yaw=2*(pitch of M1) -- this is how the beam goes up after M1 -- and then pitch of M2.

Giving *f1* of M2 equal to that of M1 is wrong. After reflection by M1 the source is not at the same point anymore but rather is an imaginary source symmetric around the M1's z=0 plain. Easier is to give a local *p* distance rather than a global source position *f1*.

**Comment by bbazi** [comment]
Hi,
Thanks for the very helpful comments!
Both mirrors look now fine in xrtGlow, only strange thing is that now it was not possible to see the footprints of both mirrors at the same time. This is something very minor but I let you know just in case.  Here's their representation:
![KBV xrtGlow](https://user-images.githubusercontent.com/82967994/125203638-8a0d9c00-e279-11eb-8a06-ac757f94e72e.png)
![KBH xrtGlow](https://user-images.githubusercontent.com/82967994/125203648-93970400-e279-11eb-89e6-08d4dcb47bec.png)
With your rotation strategy, I adapted the code as follows (yaw had to be negative though) and got the following focal point:
`       

        beamLine, 'KBV', [0, 61000., height],
            surface=('Rh',), material=(stripeRh,),
            limPhysX=(-13., 13.), limPhysY=(-70., 70.),
            pitch=3.5e-3, p=2000., q=310.,
            isCylindrical=True, alarmLevel=0.)

        beamLine.kbh = roe.EllipticalMirrorParam(
            beamLine, 'KBH', [0, 61110., height],
            surface=('Rh',), material=(stripeRh,),
            limPhysX=(-13., 13.), limPhysY=(-35., 35.),
            positionRoll=math.pi/2,
            yaw=-2*3.5e-3, pitch=3.5e-3,
            p=2110., q=200.,
            isCylindrical=True, alarmLevel=0.)`
![3 5mrad-05-18keV-03FSM-SampleE](https://user-images.githubusercontent.com/82967994/125203806-6d259880-e27a-11eb-9ef4-186818c5a1e5.png)

If I have misinterpreted your rotation strategy, please let me know. I changed the code as follows and got the results I was actually expecting. Would be nice to have your feedback on this.
`       

        beamLine, 'KBV', [0, 61000., height],
            surface=('Rh',), material=(stripeRh,),
            limPhysX=(-13., 13.), limPhysY=(-70., 70.),
            pitch=3.5e-3, p=2000., q=310.,
            isCylindrical=True, alarmLevel=0.)

        beamLine.kbh = roe.EllipticalMirrorParam(
            beamLine, 'KBH', [0, 61110., height],
            surface=('Rh',), material=(stripeRh,),
            limPhysX=(-13., 13.), limPhysY=(-35., 35.),
            positionRoll=math.pi/2,
            yaw=-3.5e-3,
            p=2110., q=200.,
            isCylindrical=True, alarmLevel=0.)`
![3 5mrad-05-18keV-03FSM-SampleE](https://user-images.githubusercontent.com/82967994/125204002-5cc1ed80-e27b-11eb-87dc-beb1d618899c.png)

**Comment by kklmn** [comment]
No, yaw should be positive. Give it a bigger value to see that the local Y of M2 bends upwards.
You don't give the described rotation order. The default one is RzRyRx, you should set RyRzRx.

**Comment by bbazi** [comment]
Oh I see, it works now.
Thanks for the great help! Cheers
