### ISSUE TITLE
xrt/gui/commons/myspyder.py fails if spyder is not installed + setup.py minor mods

### ISSUE THREAD

**Issue by maurov** [kklmn/xrt#9]
Hello,

I found `xrt/gui/commons/myspyder.py` fails if spyder is not installed.

In particular here:

```
try:
    from spyder.config.base import get_module_source_path
except ImportError:
    from spyderlib.config.base import get_module_source_path
```

Probably the best is to make a dependency of xrt on spyder officially in the documentation.

I also had to change a couple of things in `setup.py` in order to install from source the last github version. Here what I modified:

```
    packages=['xrt', 'xrt.backends', 'xrt.backends.raycing',\
              'xrt.gui.commons', 'xrt.gui.xrtQook', 'xrt.gui.xrtGlow'],
    package_data={
        'xrt.backends.raycing': [os.path.join('data', '*.*'), '*.cl'],
        'xrt': ['*.cl, *.ico'],
        'xrt.gui.xrtQook': [os.path.join('_icons', '*.*'),
                            os.path.join('_images', '*.*'),
                            os.path.join('xmls', '*.*')]},
    scripts=[os.path.join('xrt', 'gui', 'xrtQookStart.pyw')],
```

**Comment by kklmn** [comment]
Hello,
xrt/gui/commons/myspyder.py was fixed 4 days ago, please get the latest version.
Spyder is not strictly required but is convenient to have.
setup.py has not been prepared for the release yet.
