### ISSUE TITLE
xrtGlow exit with -107374091

### ISSUE THREAD

**Issue by leahwang1962** [kklmn/xrt#94]
Hello,
Does anyone have the similar experience when clicking 3D glasses button, the XRTQook will close(exit) with -107374091 displayed on python command prompt but without any trace? Any information is appreciated.
Thanks.

**Comment by kklmn** [comment]
Hi,
What do you see in xrtQook Welcome Screen under "Your system"? Nothing marked as "not installed"?

**Comment by leahwang1962** [comment]
No . everything installed correctly.
The welcome screen is like below:
Created by Roman Chernikov (Canadian Light Source)
Konstantin Klementiev (MAX IV Laboratory)

License
MIT License, March 2016

Your system
Windows-10, Python 3.10.2
Qt 5.15.2, PyQt5 5.15.6
OpenGL 3.1.5
pyopencl 2022.1
xrt 1.4.0 in C:\\Python\\lib\\site-packages, this is the latest version at PyPI

**Comment by leahwang1962** [comment]
Hello,
I tried to run 'xrtQookStart.py' instead of 'xrtQookStart.pyw', and I got the following trace. Hope it is helpful to point to the root cause.

>>> os.system('xrtQookStart.py')
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\xrt\gui\xrtQook\__init__.py", line 3375, in blRunGlow
    self.blViewer = xrtglow.xrtGlow(self.rayPath, self)
  File "C:\Python\lib\site-packages\xrt\gui\xrtGlow\__init__.py", line 102, in __init__
    self.makeTransformationPanel()
  File "C:\Python\lib\site-packages\xrt\gui\xrtGlow\__init__.py", line 205, in makeTransformationPanel
    axSlider.setRange(0, 7, 0.01)
  File "C:\Python\lib\site-packages\xrt\gui\commons\qt.py", line 120, in setRange
    QSlider.setRange(self, start / step, end / step)
TypeError: setRange(self, int, int): argument 2 has unexpected type 'float'
-1073740791

**Comment by kklmn** [comment]
Please try the GitHub version.

**Comment by leahwang1962** [comment]
I think this error is related with the definition of class slider(Qtwidgets.QSlider) , something like self.setRange(0, int,int). Does anyone know in which file I can find this class definition, or how I can update it.

**Comment by kklmn** [comment]
Probably PyQt went more strict in the last versions in interpreting the parameters of QSlider.setRange. They indeed should be ints. The fact that it doesn't throw a valid Python exception but rather a Qt exit code suggests that the Python binding is wrong or incomplete or wrongly installed.
I will put the type conversion there, thank you for finding it!
