### ISSUE TITLE
going from python script to Gui

### ISSUE THREAD

**Issue by leahwang1962** [kklmn/xrt#97]
Hello, I just realized the old issue with the same title is closed, so I start a new one. Basically my questions are following the old discussion. Thanks.

For MontelMirror,py, I changed showIn3D=true, however I got the error as shown below.
I saw in the above message "I can add an inverse function, XML generator from an existing script if anyone's interested". Like to know if it is available now.
Can I add Gaussian source in XRTQoot when add source while right click beamline?

File "C:\Pycharm\Projects\20220222_xrt\xrt\gui\xrtGlow_init_.py", line 349, in makeColorsPanel
self.paletteWidget.setSizePolicy(qt.QSizePolicy.Maximum,
TypeError: 'PySide6.QtWidgets.QWidget.setSizePolicy' called with wrong argument types:
PySide6.QtWidgets.QWidget.setSizePolicy(Policy, Policy)
Supported signatures:
PySide6.QtWidgets.QWidget.setSizePolicy(PySide6.QtWidgets.QSizePolicy)
PySide6.QtWidgets.QWidget.setSizePolicy(PySide6.QtWidgets.QSizePolicy.Policy, PySide6.QtWidgets.QSizePolicy.Policy)

**Comment by kklmn** [comment]
Hi,

I've been trying to run xrtQook in PySide6 environment, and after already many patches into the code and one day work I still cannot make it properly work and I give up.

So, we don't support PySide6 for now. I guess we will return to this issue later.
