### ISSUE TITLE
Permission denied when xrtQookPage.rst not writable

### ISSUE THREAD

**Issue by schluenz** [kklmn/xrt#99]
in a "shared" installation of xrt, xrtQook would fail with 

`PermissionError: [Errno 13] Permission denied: '.../xrt/gui/commons/_sources/xrtQookPage.rst'`

for users lacking write-permission on xrtQookPage.rst. I usually get rid of the issue by patching ext.py

```
--- xrt/gui/commons/ext.py.orig
+++ xrt/gui/commons/ext.py
@@ -30,8 +30,8 @@ except (ImportError, KeyError):
     except (ImportError, KeyError):
         isSpyderConsole = False
 
-isSphinx = True
 CONFDIR = osp.dirname(osp.abspath(__file__))
+isSphinx = os.access(CONFDIR, os.W_OK) 
 CSS_PATH = osp.join(CONFDIR, '_static')
 CSS_PATH = re.sub('\\\\', '/', CSS_PATH)
 JS_PATH = CSS_PATH
```

It's simple enough, but might be worthwhile to change it "globally"

**Comment by kklmn** [comment]
Hi!

Thank you for pointing to the problem!

Your solution simply forbids the HTML builder, which is not ideal. I've moved the build directory to a user location, it must be always accessible:
```
DOCDIR = osp.expanduser(osp.join('~', '.xrt', 'doc'))
```
Please give it a try from GitHub.

**Comment by kklmn** [comment]
Thank you again! I was too quick. It is fixed now.

**Comment by schluenz** [comment]
perfect! thanks for the quick fix.
